### PR TITLE
Shutdown fixes

### LINKED ISSUE #1679: stoping flynn-host with upstart takes long time
```sudo stop flynn-host``` returns before flynn-host is stopped. When it returns I can still visit http://my-app.demo.localflynn.com though it responds with a 500 "Service Unavailable".

### PR DESCRIPTION
**Pull request by lmars**
See commit messages.

Closes #1679.

### CODE REVIEW

File: host/host.go [hunk 1]
```diff
@@ -221,11 +222,40 @@ func runDaemon(args *docopt.Args) {
...
+		status:  &host.HostStatus{ID: hostID, URL: publishURL},
+	}
+
+	// stopJobs stops all jobs, leaving discoverd until the end so other
+	// jobs can unregister themselves on shutdown.
+	stopJobs := func() (err error) {
+		var except []string
+		host.statusMtx.RLock()
+		if host.status.Discoverd != nil && host.status.Discoverd.JobID != "" {
+			except = []string{host.status.Discoverd.JobID}
```
Comment (titanous) [inline host/host.go]: Does this pick up subsequent instances of discoverd after the first?

Comment (lmars) [inline host/host.go]: Yep each new discoverd process will send its config, which will [overwrite previous configuration](https://github.com/flynn/flynn/blob/shutdown-fixes/host/http.go#L186-L194).

**Comment by titanous** [comment]
LGTM
