### PR TITLE
cli: Implement app export/import

### LINKED ISSUE #1473: Create migration path between clusters
We need a migration path between clusters, preferably one which can handle both system-wide and individual applications. This has many things in common with #1244: a restore from backup is functionally equivalent to migration from a prior cluster.

A naive `for app in router controller blobstore; do flynn -c default -a $app pg dump | flynn -c new -a $app pg restore; done` fails, with the following results:
```
0 B                                                                                                                                                                                                                                                                    pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 5; 2615 2200 SCHEMA public postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
    Command was: DROP SCHEMA public;

13.74 KB 5.72 KB/s                                                                                                                                                                                                                                                     pg_restore: [archiver (db)] could not execute query: ERROR:  schema "public" already exists
    Command was: CREATE SCHEMA public;



pg_restore: [archiver (db)] Error from TOC entry 2079; 0 0 COMMENT SCHEMA public postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
    Command was: COMMENT ON SCHEMA public IS 'standard public schema';



pg_restore: [archiver (db)] Error from TOC entry 2080; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';



pg_restore: [archiver (db)] Error from TOC entry 2081; 0 0 COMMENT EXTENSION "uuid-ossp" 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension uuid-ossp
    Command was: COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';



WARNING: errors ignored on restore: 5
27.98 KB 12.71 KB/s                                                                                                                                                                                                                                                    pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 5; 2615 2200 SCHEMA public postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
    Command was: DROP SCHEMA public;

pg_restore: [archiver (db)] could not execute query: ERROR:  schema "public" already exists
    Command was: CREATE SCHEMA public;



pg_restore: [archiver (db)] Error from TOC entry 2334; 0 0 COMMENT SCHEMA public postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
    Command was: COMMENT ON SCHEMA public IS 'standard public schema';



pg_restore: [archiver (db)] Error from TOC entry 2335; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';



56.47 KB 23.50 KB/s                                                                                                                                                                                                                                                    pg_restore: [archiver (db)] Error from TOC entry 2336; 0 0 COMMENT EXTENSION hstore 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension hstore
    Command was: COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';



pg_restore: [archiver (db)] Error from TOC entry 2337; 0 0 COMMENT EXTENSION "uuid-ossp" 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension uuid-ossp
    Command was: COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';



WARNING: errors ignored on restore: 6
error getting app release: unknown_error: Something went wrong
0 B 1s                                                                                                                                                                                                                                                                 write /dev/stdout: broken pipe
```

### PR DESCRIPTION
**Pull request by titanous**
`flynn export` exports the app config, slug, and database to a local tar file that can be imported into any other Flynn cluster using `flynn import`.

`flynn import` creates a new app using a tar file from `flynn export`. This allows cloning and migration of apps between clusters.

/cc @temujin9 

Closes #1473

### CODE REVIEW

**Comment by temujin9** [comment]
Wohoo! Thank you. Looking forward to the seamless cluster swings this should enable.

**Comment by temujin9** [comment]
FYI: manual test of migration across clusters works as expected. Thanks again, looking forward to seeing this in mainline soon.

File: cli/export.go [hunk 1]
```diff
@@ -0,0 +1,431 @@
...
+	-f, --file=<file>  name of file to import from (defaults to stdin)
+	-n, --name=<name>  name of app to create (defaults to exported app name)
+	-q, --quiet        don't print progress
+`)
+}
+
+func runExport(args *docopt.Args, client *controller.Client) error {
+	var dest io.Writer = os.Stdout
+	if filename := args.String["--file"]; filename != "" {
+		f, err := os.Create(filename)
```
Comment (lmars) [inline cli/export.go]: I think we should ask for confirmation if the output file already exists.

File: cli/export.go [hunk 2]
```diff
@@ -0,0 +1,431 @@
...
+		}
+		if artifact.URI == "" {
+			return fmt.Errorf("gitreceive env missing SLUGRUNNER_IMAGE_URI")
+		}
+		release.Env["SLUG_URL"] = fmt.Sprintf("http://blobstore.discoverd/%s.tgz", random.UUID())
+	}
+
+	if artifact != nil {
+		if err := client.CreateArtifact(artifact); err != nil {
+			return fmt.Errorf("error creating release: %s", err)
```
Comment (lmars) [inline cli/export.go]: s/release/artifact

**Comment by lmars** [comment]
LGTM pending minor comments

File: cli/export.go (hunk 1 above)
Comment (titanous) [inline cli/export.go]: I don't think very many Unix-style tools do this. Also, it doesn't match the existing behavior of `flynn pg dump`.

Comment (lmars) [inline cli/export.go]: :+1:
