### PR TITLE
installer: Configure CLI

### LINKED ISSUE #1303: Installer doesn't configure CLI cluster
After the installer succeeds, it should configure the CLI for access to the cluster. This is a regression, as it used to do this before the web GUI landed.

### PR DESCRIPTION
**Pull request by jvatic**
refs 67e39ebebccc5dbb550ae694b4027dc249b779d7
fixes #1303

### CODE REVIEW

File: cli/config/config.go [hunk 1]
```diff
@@ -23,6 +25,23 @@ type Config struct {
 	Clusters []*Cluster `toml:"cluster"`
 }
 
+// copied from cli/main.go
+func homedir() string {
```
Comment (jvatic) [inline cli/config/config.go]: Is there any reason not to use [`os/user.Current()`](http://golang.org/pkg/os/user/#Current) here?

Comment (titanous) [inline cli/config/config.go]: I don't think so, the new cross-compilation setup should allow it to work. Just make sure you test with a cross-compiled binary and it works.

**Comment by titanous** [comment]
LGTM
