### PR TITLE
Host refactor

### LINKED ISSUE #1373: flynn-host cluster refactor
After attempting to implement #1170 a few different ways, and observing some production failures of sampi, I have a new plan.

In the new model, each `flynn-host` instance exposes an API that can be used to run jobs on that instance.

The concept of a cluster state leader (`sampi`) is removed and replaced with a set of "monitors" that keep track of the cluster state. The sampi model had a serious failing in that it made it appear that there is a consistent view of the cluster, when that is not actually true. At any point in time there may be hosts that are not connected to sampi due to a network partition or other issues. Hosts could also disconnect during scheduling, causing requested jobs to never be run. Since pretending that there is a consistent cluster state only complicates things, we can switch to an eventually consistent model. The first iteration will have "monitor" instances that discover hosts via service discovery and unify the state from all of them in memory. To run jobs, the scheduler must connect to the target host and request that the jobs be run. Since the scheduler needs to connect to the host anyway to monitor the job, this has basically no impact.

Layer 0 bootstrap is removed entirely, and the concept of layer 0 mostly disappears. All services, including discoverd, etcd, and flannel are started by bootstrap. A discovery URL or list of `flynn-host` IPs is passed to bootstrap in order to find all of the nodes. This simplifies bootstrap and allows us to have tighter control over the process without splitting configuration across multiple steps (no more implicit layer 0 bootstrap + etcd config). The user experience is also better because we can health check etcd/flannel while starting them, and expose any error logs and diagnostics right away (#1148). It also becomes much easier to register everything in the controller for management and updates, and move to idempotent bootstrap (#225) in the future.

In the future, we'll want to apply policy across the cluster to schedulers (for example limiting the total amount of resources allowed). This will be accomplished by having a set of "arbiter" services that watch trusted monitors. In order to schedule a new job or resize an existing job, a scheduler will provide details to and request a ticket from the arbiter. The ticket will time-limited and be accepted by the specified host, providing permission to access the resources.

**TODO**

- [x] Remove sampi, and modify each host to be standalone, capable of running jobs via its API.
- [x] Remove layer 0 bootstrap.
- [x] Implement discovery URL system for hosts.
- [x] Add API to configure networking, remove knowledge of flannel.
- [x] Add API to configure discoverd registration.
- [x] Move etcd, discoverd, flannel to bootstrap, register in controller.
- [x] Update scheduler.
- [x] Update all consumers of the cluster API to use the new system.

### LINKED ISSUE #1545: No hosts found when pushing to Flynn
I've setted up my app correctly, I got it up and running, and even succeded deploying my app using flynn, twice.

However, the third time that I tried to deploy, I run into the following issue:

    ➜  webscrap_master_service git:(master) git push flynn master                                         
    Counting objects: 11, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (6/6), done.
    Writing objects: 100% (6/6), 582 bytes | 0 bytes/s, done.
    Total 6 (delta 4), reused 0 (delta 0)
    -----> Building webscrap...
    -----> Fetching custom buildpack
    -----> Ruby app detected
    -----> Compiling Ruby/Rails
    -----> Using Ruby version: ruby-2.1.2
    -----> Installing dependencies using 1.9.6
           Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
           Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
           Using CFPropertyList 2.3.1
           Using i18n 0.7.0
           Using rake 10.4.2
           Using json 1.8.2
           Using minitest 5.6.1
           Using thread_safe 0.3.5
           Using builder 3.2.2
           Using erubis 2.7.0
           Using mini_portile 0.6.2
           Using rack 1.6.0
           Using mime-types 2.5
           Using arel 6.0.0
           Using hitimes 1.2.2
           Using coffee-script-source 1.9.1.1
           Using execjs 2.5.2
           Using thor 0.19.1
           Using commonjs 0.2.7
           Using connection_pool 2.2.0
           Using daemons 1.2.2
           Using unf_ext 0.0.7.1
           Using excon 0.45.3
           Using multipart-post 2.0.0
           Using formatador 0.2.5
           Using net-ssh 2.9.2
           Using multi_json 1.11.0
           Using ipaddress 0.8.0
           Using inflecto 0.0.2
           Using hike 1.2.3
           Using tilt 1.4.1
           Using libv8 3.16.14.7
           Using net-http-digest_auth 1.4
           Using net-http-persistent 2.9.4
           Using ntlm-http 0.1.1
           Using webrobots 0.1.1
           Using pg 0.18.1
           Using bundler 1.9.6
           Using rails_serve_static_assets 0.0.4
           Using rails_stdout_logging 0.0.3
           Using redis 3.2.1
           Using ref 1.0.5
           Using rubyzip 1.1.7
           Using sass 3.2.19
           Using temple 0.7.5
           Using fission 0.5.0
           Using tzinfo 1.2.2
           Using nokogiri 1.6.6.2
           Using rack-test 0.6.3
           Using puma 2.11.2
           Using rack-protection 1.5.3
           Using mail 2.6.3
           Using timers 4.0.1
           Using coffee-script 2.4.1
           Using uglifier 2.7.1
           Using figaro 1.1.1
           Using less 2.6.0
           Using unf 0.1.4
           Using faraday 0.9.1
           Using net-scp 1.2.1
           Using sprockets 2.12.3
           Using redis-namespace 1.5.2
           Using rails_12factor 0.0.3
           Using activesupport 4.2.1
           Using loofah 2.0.1
           Using therubyracer 0.12.2
           Using celluloid 0.16.0
           Using slim 3.0.3
           Using domain_name 0.5.24
           Using fog-core 1.30.0
           Using sinatra 1.4.6
           Using rails-deprecated_sanitizer 1.0.3
           Using globalid 0.3.5
           Using activemodel 4.2.1
           Using rails-html-sanitizer 1.0.2
           Using sidekiq 3.3.4
           Using http-cookie 1.0.2
           Using fog-xml 0.1.2
           Using fog-json 1.0.1
           Using fog-local 0.2.1
           Using fog-vmfusion 0.1.0
           Using rails-dom-testing 1.0.6
           Using activejob 4.2.1
           Using activerecord 4.2.1
           Using fog-brightbox 0.7.1
           Using fog-sakuracloud 1.0.1
           Using fog-serverlove 0.1.2
           Using fog-softlayer 0.4.5
           Using fog-storm_on_demand 0.1.1
           Using fog-atmos 0.1.0
           Using fog-aws 0.1.2
           Using fog-ecloud 0.1.1
           Using fog-powerdns 0.1.1
           Using fog-profitbricks 0.0.2
           Using fog-radosgw 0.0.4
           Using fog-riakcs 0.1.0
           Using fog-terremark 0.1.0
           Using fog-voxel 0.1.0
           Using actionview 4.2.1
           Using mechanize 2.7.3
           Using actionpack 4.2.1
           Using fog 1.29.0
           Using swiffer 1.1.9
           Using actionmailer 4.2.1
           Using railties 4.2.1
           Using less-rails 2.7.0
           Using sprockets-rails 2.2.4
           Using coffee-rails 4.0.1
           Using jquery-rails 4.0.3
           Using rails 4.2.1
           Using sass-rails 4.0.5
           Using slim-rails 3.0.1
           Using twitter-bootstrap-rails 3.2.0
           Bundle complete! 25 Gemfile dependencies, 111 gems now installed.
           Gems in the groups development and test were not installed.
           Bundled gems are installed into ./vendor/bundle.
           Bundle completed (1.14s)
           Cleaning up the bundler cache.
           Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
    -----> Preparing app for Rails asset pipeline
           Running: rake assets:precompile
           Asset precompilation completed (2.89s)
           Cleaning assets
           Running: rake assets:clean
           
    -----> Discovering process types
           Procfile declares types -> web, worker
           Default process types for Ruby -> rake, console, web, worker
    -----> Compiled slug size is 53M
    remote: Build failed: exec: job exited with status 23
    To ssh://git@services.textmaster.com:2222/webscrap.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'ssh://git@services.textmaster.com:2222/webscrap.git' 

I retried again, without any further modification, and now I got a new error:

	➜  webscrap_master_service git:(master) git push flynn master
	Counting objects: 11, done.
	Delta compression using up to 8 threads.
	Compressing objects: 100% (6/6), done.
	Writing objects: 100% (6/6), 582 bytes | 0 bytes/s, done.
	Total 6 (delta 4), reused 0 (delta 0)
	-----> Building webscrap...
	remote: Build failed: exec: no hosts found
	To ssh://git@services.textmaster.com:2222/webscrap.git
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'ssh://git@services.textmaster.com:2222/webscrap.git'

Here is my debug information link:  https://gist.github.com/60ebe72ee3fc6a54ec2f 

So, I can't can't deploy my new commits using flynn, because of those errors.
Thanks you

PS: Here is the custom buildpack, nothing fancy (upgrading Bundler): https://github.com/gottfrois/heroku-buildpack-ruby 

PS2: I also got the logs of the second time that I've succeeded in deploying with Flynn:
https://gist.github.com/shideneyu/7897c1b891973af36dcf

PS3:

    ~$ flynn-host version
    v20150515.0

### LINKED ISSUE #1573: Failed to run remote commands
Hi, suddenly I can't run commands like `flynn run something`, or `flynn pg psql`, or `flynn pg dump -f latest.dump`. I returns `unknown_error: Something went wrong`. Every other commands works. Well I didn't try scaling, I don't want to push my luck and break it even more :)

Here is my debug info https://gist.github.com/e1394f4ea95f5d95ca85

Thanks

### PR DESCRIPTION
**Pull request by titanous**
Closes #1373.
Closes #1573.
Closes #1545.

Sorry about the huge diff :sob:

Major points:

- Sampi is totally removed, each host only cares about its own state
- Flannel and discoverd send webhooks to flynn-host when starting to configure
- There is no layer 0 bootstrap, the `flynn-host bootstrap` command is responsible for starting everything
- [flynn-discovery](https://github.com/flynn/flynn-discovery/pull/1) replaces etcd discovery

### CODE REVIEW

File: host/discoverd.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+	defer d.mtx.Unlock()
+	return d.local != nil
+}
+
+func (d *DiscoverdManager) ConnectLocal(url string) error {
+	if d.localConnected() {
+		return errors.New("host: discoverd is already configured")
+	}
+	disc := discoverd.NewClientWithURL(url)
+	// TODO: use attempts to connect
```
Comment (lmars) [inline host/discoverd.go]: discoverd should probably use a retry dialer like [the controller client](https://github.com/flynn/flynn/blob/master/controller/client/client.go#L134).

File: test/cluster/cluster.go [hunk 2]
```diff
@@ -447,8 +446,6 @@ if [[ -f test/scripts/debug-info.sh ]]; then
 fi
 
 sudo cp host/bin/flynn-* /usr/local/bin
-sudo cp host/bin/manifest.json /etc/flynn-host.json
-sudo cp bootstrap/bin/manifest.json /etc/flynn-bootstrap.json
```
Comment (lmars) [inline test/cluster/cluster.go]: We still need the bootstrap manifest right?

Comment (lmars) [inline test/cluster/cluster.go]: Fixed in 2e0a279

**Comment by lmars** [comment]
LGTM !!!
