### PR TITLE
host/cli: Be more verbose in upload-debug-info

### LINKED ISSUE #1215: Host fails to upload debug info.
Running `flynn-host upload-debug-info` produces:

```
23:33:32.334497 upload-debug-info.go:48: error adding tmp-flynn-host.log: open /tmp/flynn-host.log: no such file or directory
```

Host is Ubuntu 14.04 LTS, 3.13.0-46-generic, x86_64.

### PR DESCRIPTION
**Pull request by lmars**
Sample output (has colour in the terminal):

```
INFO[03-11|16:48:56] uploading logs and debug information to a private, anonymous gist 
INFO[03-11|16:48:56] this may take a while depending on the size of your logs 
INFO[03-11|16:48:56] getting flynn-host logs 
EROR[03-11|16:48:56] error getting flynn-host log "/var/log/upstart/flynn-host.log" err="open /var/log/upstart/flynn-host.log: no such file or directory"
INFO[03-11|16:48:56] getting job logs 
INFO[03-11|16:48:56] getting system information 
INFO[03-11|16:48:57] creating anonymous gist 
223.56 KB / 223.56 KB [===========================================================================================================] 100.00 % 51.57 KB/s 4s
INFO[03-11|16:49:01] debug information uploaded to: https://gist.github.com/12d294317f57028232f5
```

The error will be gone once #1218 is merged.

Fixes #1215.

### CODE REVIEW

**Comment by titanous** [comment]
Needs a rebase.

File: host/cli/gist.go [hunk 1]
```diff
@@ -29,31 +35,49 @@ func (g *Gist) AddFile(name, content string) {
...
 	if err != nil {
+		log.Error("error preparing gist content", "err", err)
 		return err
 	}
-	req, err := http.NewRequest("POST", "https://api.github.com/gists", bytes.NewReader(payload))
+	var body io.Reader = bytes.NewReader(payload)
+	if term.IsTerminal(os.Stderr.Fd()) {
+		bar := pb.New(0)
+		bar.SetUnits(pb.U_BYTES)
+		bar.Total = int64(len(payload))
```
Comment (titanous) [inline host/cli/gist.go]: Just pass this in to `pb.New`

**Comment by titanous** [comment]
LGTM pending comment.
