### PR TITLE
Postgres deployment fixes

### LINKED ISSUE #1661: When updating I get the error "pg cluster in unhealthy state"
pg cluster in unhealthy state (too few syncs)

https://gist.github.com/3266345d084810a50b51

### PR DESCRIPTION
**Pull request by lmars**
Closes #1661.

### CODE REVIEW

File: controller/worker/deployment/postgres.go [hunk 1]
```diff
@@ -48,6 +49,10 @@ func (d *DeployJob) deployPostgres() (err error) {
 	if 2+len(state.Async) != d.Processes["postgres"] {
 		return loggedErr(fmt.Sprintf("pg cluster in unhealthy state (too few asyncs)"))
 	}
+	if reflect.DeepEqual(d.newReleaseState, d.Processes) {
```
Comment (titanous) [inline controller/worker/deployment/postgres.go]: Don't use `reflect` if you don't have to. In this case it's a bit more code, but we can have a type-safe comparison.

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM
