### PR TITLE
host: Clean up mounts that leak into libvirt_lxc

### LINKED ISSUE #1125: HostSuite.TestVolumePersistence failure
```text
FAIL: test_host.go:165: HostSuite.TestVolumePersistence

test_host.go:208:
    ...
test_host.go:176:
    t.Assert(h.DestroyVolume(vol.ID), c.IsNil)
... value httphelper.JSONError = httphelper.JSONError{Code:"unknown_error", Message:"Something went wrong", Detail:json.RawMessage(nil)} ("unknown_error: Something went wrong")
```

https://ci.flynn.io/builds/20150302072334-e3c6b69f

### PR DESCRIPTION
**Pull request by titanous**
When a mount namespace is created, it inherits all of the mounts from its parent. If they are not `umount(2)`'ed, they will remain and prevent devices from being cleaned up. This currently causes problems when destroying ZFS volumes and cleaning up temporary container rootfs mountpoints.

The libvirt-lxc container system creates two mount namespaces for each container: one in the `libvirt_lxc` supervisor process, and one in the process that execs the actual container process. The latter cleans up the mounts that leak in, but the former does not. This is tracked upstream at https://bugzilla.redhat.com/show_bug.cgi?id=1067489

We work around this issue by adding a small `flynn-nsumount` executable that can reach into an arbitrary mount namespace (using a pid) and call `umount(2)` against a list of paths. This executable is called immediately after launching each libvirt-lxc container to clean up any leaked mountpoints that are known to cause trouble with flynn.

Note that this is not a complete fix, just a temporary band-aid. The following issues remain:

- Any devices such as USB drives will not be automatically cleaned
  up, as we only unmount paths that we know we control. This could
  probably be solved, but the hope is that this workaround will not
  be required for very long.
- There is a non-zero time period between creating the namespace and
  unmounting the leaked mounts, which could cause a race with
  processes that are destroying mounts. In practice this probably
  won't happen and can be worked around by retrying requests.

Closes #1125

### CODE REVIEW

File: host/cli/download.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ func runDownload(args *docopt.Args) error {
 	if err := os.MkdirAll(args.String["--bin-dir"], 0755); err != nil {
 		return fmt.Errorf("error creating bin dir: %s", err)
 	}
-	for _, path := range []string{"/flynn-linux-amd64", "/flynn-init"} {
+	for _, path := range []string{"/flynn-linux-amd64", "/flynn-init", "/nsumount"} {
```
Comment (lmars) [inline host/cli/download.go]: The path should be `/flynn-nsumount`

**Comment by lmars** [comment]
LGTM pending comment

File: host/libvirt_lxc_backend.go [hunk 2]
```diff
@@ -612,6 +626,27 @@ func (l *LibvirtLXCBackend) openLog(id string) *logbuf.Log {
...
+	args := make([]string, 1, len(list)+1)
+	args[0] = strconv.Itoa(pid)
+	for _, m := range list {
+		if strings.HasPrefix(m.Mountpoint, imageRoot) || strings.HasPrefix(m.Mountpoint, flynnRoot) {
+			args = append(args, m.Mountpoint)
+		}
+	}
+
+	if err := exec.Command(c.l.UmountPath, args...).Run(); err != nil {
+		return fmt.Errorf("host: error running nsumount %s: %s", pid, err)
```
Comment (lmars) [inline host/libvirt_lxc_backend.go]: The pid format should be `%d`

**Comment by lmars** [comment]
@titanous CI build [20150708185342-5617bb11](https://ci.flynn.io/builds/20150708185342-5617bb11) failed to start two blobstore jobs in the release cluster, with the following errors in the host logs:

```
now=2015-07-08T18:59:25+0000 err="host: error running nsumount %!s(int=4713): exit status 1" at=cleanup_mounts app=host job.id=df56904b-eeeaca59951e4cceb05372b6142b0b7c backend=libvirt-lxc fn=run status=error

now=2015-07-08T18:59:25+0000 app=host fn=run job.id=df56904b-951251a16962410d9f94f509bddcf6e9 backend=libvirt-lxc at=cleanup_mounts status=error err="host: error running nsumount %!s(int=4631): exit status 1"
```

Not very informative, we should probably log the output of the command.

**Comment by titanous** [comment]
Updated to attempt to unmount every path, print all errors, and not blow up if there are errors (since this is a best effort thing anyway).

**Comment by titanous** [comment]
I moved the unmount code and added some more cleanup (fixing a major pinkerton cleanup bug along the way). I believe this is ready to merge.

File: host/libvirt_lxc_backend.go [hunk 3]
```diff
@@ -665,6 +698,18 @@ func (c *libvirtContainer) watch(ready chan<- error) error {
...
 
+	go func() {
+		// Workaround for mounts leaking into the libvirt_lxc supervisor process,
+		// see https://github.com/flynn/flynn/issues/1125 for details. Remove
+		// nsumount from the tree when deleting.
+		g.Log(grohl.Data{"at": "cleanup_mounts", "status": "start"})
+		if err := c.cleanupMounts(c.domain.ID); err != nil {
+			g.Log(grohl.Data{"at": "cleanup_mounts", "status": "error", "err": err})
+		}
+		c.unbindMounts()
```
Comment (lmars) [inline host/libvirt_lxc_backend.go]: It took me a minute to realise why we are immediately unbinding all the mounts, so I think this could do with a comment that by this point, the mount namespace has been cloned and these are no longer necessary in the root namespace.

**Comment by lmars** [comment]
LGTM pending comment
