### PR TITLE
router: Use prepared queries

### LINKED ISSUE #3179: Router fails to load path-based routes
Restarting the router after adding a path-based route can sometimes result in this error and the route not getting loaded:

```text
Failed insert of path based route, consistency violation.
```

The problem appears to be that it is assumed that the path-based route will always be loaded after the parent bare domain route. This assumption does not hold, resulting in a failure to load the route.

As a very temporary workaround, the path-based route can be removed and re-added after restarting the router.

### PR DESCRIPTION
**Pull request by josephglanville**
Updates the router datastore to use prepared queries.

Closes #3179

### CODE REVIEW

**Comment by titanous** [comment]
LGTM

File: router/setup_test.go [hunk 1]
```diff
@@ -88,6 +90,13 @@ func (s *S) SetUpSuite(c *C) {
 	if err = migrateDB(db); err != nil {
 		c.Fatal(err)
 	}
+	db.Close()
+
+	// reconnect with prepared statements
+	pgxConfig.AfterConnect = schema.PrepareStatements
+	pgxpool, err = pgx.NewConnPool(pgxConfig)
```
Comment (titanous) [inline router/setup_test.go]: err is unchecked
