### PR TITLE
router: Handle route deletions missed on reconnect

### LINKED ISSUE #1002: router: recover missed route deletions after sync failure
`DataStore` uses a `LISTEN` connection to watch for route changes. This connection will occasionally fail, and to recover the `DataStore` must restart the `LISTEN` connection then do a full-sync of all routes to pickup routes added while the `LISTEN` connection dropped.

This recovery strategy currently has a flaw which causes routes to never be removed if the remove is issued during a window when the `LISTEN` connection has failed and the `DataStore` has not detected the failure.

In order to solve this, the Sync API, which is currently asynchronous (`StartSync`/`StopSync`), needs to be synchronous (`Sync`), so that the caller (`HTTPListener`/`TCPListener`) can be notified of errors. This allows the caller to rebuild it's routing state from scratch when `Sync` fails. Furthermore, the caller should be capable of rebuilding the routing state without having to lock routing.

### PR DESCRIPTION
**Pull request by josephglanville**
This tracks which routes were removed while the sync is disconnected and removes them on reconnect.
Right now on reconnect we still fetch the entire route table from the database.

Closes #1002

### CODE REVIEW

**Comment by josephglanville** [comment]
There is a further change needed to make syncing safer for path based routes which involves sorting them before insertion into the routing trie.

I had a bigger overhaul in mind but it was a little ambitious so scaling back to fixing the correctness issues first.

**Comment by josephglanville** [comment]
A bit of thought might actually suggest no changes are needed, because of the strict insertion/deletion order enforced by the constraint trigger. I will try modify the test to see if I can break it.

File: router/http_test.go [hunk 1]
```diff
@@ -313,6 +316,123 @@ func (s *S) TestHTTPInitialSync(c *C) {
 	assertGet(c, "https://"+l.TLSAddr, "example.com", "1")
 }
 
+func (s *S) TestHTTPResync(c *C) {
+	connPids := make([]int32, 0)
```
Comment (titanous) [inline router/http_test.go]: Don't use `make` with `len = 0`:

```go
var connPids []int32
```

File: router/http_test.go [hunk 2]
```diff
@@ -313,6 +316,123 @@ func (s *S) TestHTTPInitialSync(c *C) {
...
+		}
+		defer conn.Close()
+
+		// terminate all conns from the pool
+		for _, pid := range connPids {
+			if _, err := conn.Exec("select pg_terminate_backend($1)", pid); err != nil {
+				c.Fatalf("Unable to kill backend PostgreSQL process: %v", err)
+			}
+		}
+		connPids = make([]int32, 0)
```
Comment (titanous) [inline router/http_test.go]: Just truncate it:

```go
connPids = connPids[:0]
```

File: router/http.go [hunk 3]
```diff
@@ -116,6 +116,10 @@ func (s *HTTPListener) startSync(ctx context.Context) error {
 	}
 }
 
+// Testing hooks
+var preResync func()
+var postResync func(startc <-chan struct{})
```
Comment (titanous) [inline router/http.go]: I'd move these to the listener struct so that multiple tests can be run concurrently.

**Comment by titanous** [comment]
LGTM
