### PR TITLE
cli: Clarify multiple remotes error

### LINKED ISSUE #1419: Multiple flynn remotes cause "multiple apps in git remotes" error
I have 2 remotes: "flynn" and "flynn-prod".

Some commands `flynn env` allow operating without specifying an app `flynn -a foo ...`. Other commands return an error: "main.go:266: multiple apps in git remotes". Since `-a foo` is the same on both clusters, nothing is disambiguated by specifying the app, but the command then works.

I'd expect all the commands just to go to the default cluster in .flynnrc, for the app name in the current git tree.

### PR DESCRIPTION
**Pull request by titanous**
Now it looks like this:

```text
error: Multiple apps listed in git remotes, please specify one with the global -a option to disambiguate.

Available remotes:
production
staging
```

Closes #1419

### CODE REVIEW

**Comment by lmars** [comment]
LGTM

File: cli/git.go [hunk 1]
```diff
@@ -117,6 +117,12 @@ func remoteFromGitConfig() string {
 	return strings.TrimSpace(string(b))
 }
 
+type multipleRemotesError []string
+
+func (remotes multipleRemotesError) Error() string {
+	return "error: Multiple apps listed in git remotes, please specify one with the global -a option to disambiguate.\n\nAvailable Flynn remotes:\n" + strings.Join(remotes, "\n")
+}
+
 var errMultipleFlynnRemotes = errors.New("multiple apps in git remotes")
```
Comment (jzila) [inline cli/git.go]: This is no longer necessary.

Comment (titanous) [inline cli/git.go]: Yep, thanks!

Comment (titanous) [inline cli/git.go]: #1433
