### PR TITLE
deployer: Wait for job events before deleting formation during rollback

### LINKED ISSUE #1160: deployer: Rolling back the controller breaks the cluster
If the controller fails to deploy, the deployer will do a rollback which calls `PutFormation` and `DeleteFormation` in quick succession (i.e. [here](https://github.com/flynn/flynn/blob/master/controller/deployer/main.go#L154-L164)) , which leads to the scheduler potentially scaling itself down before it has started new schedulers to replace itself, leaving the cluster in a broken state.

### PR DESCRIPTION
**Pull request by jvatic**
Closes #1160 

- [x] Write test

### CODE REVIEW

File: controller/events.go [hunk 1]
```diff
@@ -155,15 +157,18 @@ func (c *controllerAPI) Events(ctx context.Context, w http.ResponseWriter, req *
 
 	if req.Header.Get("Accept") == "application/json" {
 		if err := listEvents(ctx, w, req, app, c.eventRepo); err != nil {
+			log.Error("Error listing events", "err", err)
```
Comment (lmars) [inline controller/events.go]: We tend to not capitalise error messages

File: test/test_scheduler.go [hunk 2]
```diff
@@ -353,6 +353,97 @@ func (s *SchedulerSuite) TestTCPApp(t *c.C) {
...
+	t.Assert(err, c.IsNil)
+	defer watcher.Close()
+
+	// get the current controller formation
+	formation, err := client.GetFormation(app.ID, release.ID)
+	t.Assert(err, c.IsNil)
+
+	currentReleaseID := release.ID
+
+	// create a controller deployment what will fail
```
Comment (lmars) [inline test/test_scheduler.go]: s/what/that

File: test/test_scheduler.go [hunk 3]
```diff
@@ -353,6 +353,97 @@ func (s *SchedulerSuite) TestTCPApp(t *c.C) {
...
+	t.Assert(err, c.IsNil)
+
+	events := make(chan *ct.DeploymentEvent)
+	eventStream, err := client.StreamDeployment(deployment, events)
+	t.Assert(err, c.IsNil)
+	defer eventStream.Close()
+
+	// wait for the deploy to complete (this doesn't wait for specific events
+	// due to the fact that when the deployer deploys itself, some events will
+	// not get sent)
```
Comment (lmars) [inline test/test_scheduler.go]: Can probably replace this comment with "wait for the deploy to fail"

File: test/test_scheduler.go [hunk 4]
```diff
@@ -353,6 +353,97 @@ func (s *SchedulerSuite) TestTCPApp(t *c.C) {
...
+			}
+			debugf(t, "got deployment event: %s %s", e.JobType, e.JobState)
+			switch e.Status {
+			case "complete":
+				t.Fatal("the deployment succeeded when it should have failed")
+			case "failed":
+				break loop
+			}
+		case <-time.After(2 * time.Minute):
+			t.Fatal("timed out waiting for the deploy to complete")
```
Comment (lmars) [inline test/test_scheduler.go]: s/complete/fail

File: test/test_scheduler.go [hunk 5]
```diff
@@ -353,6 +353,97 @@ func (s *SchedulerSuite) TestTCPApp(t *c.C) {
...
+	}
+
+	// wait for jobs to come back up
+	hosts, err := s.clusterClient(t).Hosts()
+	expected := map[string]map[string]int{
+		currentReleaseID: {
+			"web":       formation.Processes["web"],
+			"worker":    formation.Processes["worker"],
+			"scheduler": len(hosts),
+		},
```
Comment (lmars) [inline test/test_scheduler.go]: Since the deploy is now sorted, won't it always deploy the scheduler and then fail at web, so only resurrect the scheduler jobs (i.e. this should just be waiting for new scheduler jobs)?

Comment (jvatic) [inline test/test_scheduler.go]: It will deploy the scheduler, web, then fail at worker.

**Comment by jvatic** [comment]
@lmars comments addressed and rebased with master

File: test/test_scheduler.go (hunk 5 above)
Comment (lmars) [inline test/test_scheduler.go]: Ah ok, for some reason I read `worker` as `web` earlier :unamused: 

Ok so in that case do we expect any new worker jobs to start? Shouldn't the old ones still be intact?

Comment (jvatic) [inline test/test_scheduler.go]: There was a typo: `worker` was being set to the web process. And yes.

**Comment by lmars** [comment]
LGTM
