### PR TITLE
deployer: Support waiting for service discovery events

### LINKED ISSUE #849: deployer: Wait for discoverd events instead of job events
Waiting for jobs allows us to catch run failures, but we are unable to detect crashes. By waiting for discoverd services to come up, we'd take care of both scenarios.

### PR DESCRIPTION
**Pull request by lmars**
Closes #849.

### CODE REVIEW

File: controller/deployer/strategies/main.go [hunk 1]
```diff
@@ -39,60 +141,87 @@ func jobEventsEqual(expected, actual jobEvents) bool {
...
+			}
+			if _, ok := d.useJobEvents[typ]; ok {
+				continue
+			}
+			log.Info("got service event", "type", typ, "state", event.Kind)
+			switch event.Kind {
+			case discoverd.EventKindUp:
+				handleEvent(typ, "up")
+			case discoverd.EventKindDown:
+				handleEvent(typ, "down")
```
Comment (titanous) [inline controller/deployer/strategies/main.go]: I think we need to always use job events to track the "down" event as an instance could go down in discoverd and then come back up.

File: host/containerinit/init.go [hunk 2]
```diff
@@ -412,20 +413,32 @@ func monitor(port host.Port, container *ContainerInit, env map[string]string) (d
...
 		}
 	}
-	addr := fmt.Sprintf("%s:%v", env["EXTERNAL_IP"], port.Port)
+	inst := &discoverd.Instance{
+		Addr:  fmt.Sprintf("%s:%v", env["EXTERNAL_IP"], port.Port),
+		Proto: port.Proto,
+	}
+	// add any Flynn environment variables to the meta
+	for k, v := range env {
+		if strings.HasPrefix(k, "FLYNN_") {
```
Comment (titanous) [inline host/containerinit/init.go]: I think we probably need a whitelist, this will pick up user-define variables as well as some other stuff that is not relevant like `FLYNN_POSTGRES`.

File: controller/deployer/strategies/main.go [hunk 3]
```diff
@@ -7,22 +7,124 @@ import (
...
+					break outer
+				}
+			case <-time.After(5 * time.Second):
+				log.Error("error creating service discovery watcher, timeout reached", "service", proc.Service)
+				return fmt.Errorf("deployer: could not create watcher for service: %s", proc.Service)
+			}
+		}
+		go func() {
+			for {
+				event, ok := <-events
```
Comment (titanous) [inline controller/deployer/strategies/main.go]: Use `range` here

File: controller/deployer/strategies/main.go [hunk 4]
```diff
@@ -39,60 +141,87 @@ func jobEventsEqual(expected, actual jobEvents) bool {
...
+func (d *Deploy) waitForJobEvents(releaseID string, expected jobEvents, log log15.Logger) error {
 	actual := make(jobEvents)
-outer:
+
+	handleEvent := func(typ, state string) {
+		if _, ok := actual[typ]; !ok {
+			actual[typ] = make(map[string]int)
+		}
+		actual[typ][state] += 1
+		d.deployEvents <- ct.DeploymentEvent{
```
Comment (titanous) [inline controller/deployer/strategies/main.go]: Should we dedup using the job ID? It seems like there are a variety of edge cases where we could get duplicate events.

File: controller/deployer/strategies/main.go (hunk 3 above)
Comment (lmars) [inline controller/deployer/strategies/main.go]: `events` is a channel, so I can't both use `range` and check for a closed channel. If you are proposing dropping the closed check, I am going to actually handle that case in a subsequent PR.

**Comment by lmars** [comment]
@titanous comments addressed

File: controller/deployer/strategies/main.go (hunk 3 above)
Comment (titanous) [inline controller/deployer/strategies/main.go]: The range loop ends when the channel closes, which seems like it would work fine?

Comment (lmars) [inline controller/deployer/strategies/main.go]: Ok, so I am going to be changing this to something like:

```go
events := make(chan *discoverd.Event)
reconnect := func() {
	stream, err := discoverd.NewService(proc.Service).Watch(events)
}
go func() {
	for {
		event, ok := <-events
		if !ok {
			reconnect()
			continue
		}
	}
}()
```

I don't mind changing for now though.

Comment (titanous) [inline controller/deployer/strategies/main.go]: Ah, that's fine. You can leave it.

File: controller/deployer/strategies/main.go [hunk 5]
```diff
@@ -7,22 +7,124 @@ import (
...
+	"github.com/flynn/flynn/discoverd/client"
 )
 
-type PerformFunc func(log15.Logger, *controller.Client, *ct.Deployment, chan<- ct.DeploymentEvent) error
+type UnknownStrategyError struct {
+	Strategy string
+}
+
+func (e UnknownStrategyError) Error() string {
+	return fmt.Sprintf(`deployer: unknown strategy "%s"`, e.Strategy)
```
Comment (titanous) [inline controller/deployer/strategies/main.go]: Could use `%q`

**Comment by titanous** [comment]
LGTM pending minor comment.
