### PR TITLE
Mongodb recovery fixes

### LINKED ISSUE #3552: 3 node cluster went down, Mongo never came back
```
shank@exo-flynn-01:~$ flynn-host --version
v20161017.1
```

Over the weekend I installed a fresh flynn cluster on three brand new Ubuntu 14.04 LTS VMs in a test environment to evaluate moving some side projects to a flynn cluster. Anyway, I got everything working using the normal docs: three flynn nodes running in one cluster with an app deployed and everything seemingly good on the dashboard.

For various reasons, I suspended the Ubuntu VMs a couple times all at once and resumed them, but later on, evidently something happened and they crashed. I rebooted the Ubuntu VMs and expected flynn to recover automatically, but it didn't. Things like the dashboard weren't working, so I googled around and found the `flynn-host fix` command and gave it a try. It seemed to resolve some issues (the dashboard and app routing were working) but Mongo never came back.

The dashboard doesn't show Mongo as a configured resource anymore, oddly enough. The health page seems to show everything but Mongo running, and `flynn-host fix -n 3` doesn't seem to help.

No apps were configured with Mongo -- I installed it from the providers page and hit provision.

screen shot 2016-10-21 at 10 06 25 pm

screen shot 2016-10-21 at 10 08 32 pm

```
shank@exo-flynn-02:~$ flynn-host fix -n 3
INFO[10-21|22:07:11] found expected hosts                     n=3
INFO[10-21|22:07:11] ensuring discoverd is running on all hosts
INFO[10-21|22:07:11] checking flannel
INFO[10-21|22:07:11] flannel looks good
INFO[10-21|22:07:11] waiting for discoverd to be available
INFO[10-21|22:07:11] checking for running controller API
INFO[10-21|22:07:11] found running controller API instances   n=2
INFO[10-21|22:07:11] found controller instance, checking critical formations
INFO[10-21|22:07:11] checking status of sirenia databases
INFO[10-21|22:07:11] checking for database state              db=postgres
INFO[10-21|22:07:11] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[10-21|22:07:11] found running leader                     fn=FixSirenia service=postgres
INFO[10-21|22:07:11] found running instances                  fn=FixSirenia service=postgres count=3
INFO[10-21|22:07:11] getting sirenia status                   fn=FixSirenia service=postgres
INFO[10-21|22:07:11] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[10-21|22:07:11] checking for database state              db=mariadb
INFO[10-21|22:07:11] skipping recovery of db, no state in discoverd db=mariadb
INFO[10-21|22:07:11] checking for database state              db=mongodb
INFO[10-21|22:07:11] checking sirenia cluster status          fn=FixSirenia service=mongodb
INFO[10-21|22:07:11] found running leader                     fn=FixSirenia service=mongodb
INFO[10-21|22:07:11] found running instances                  fn=FixSirenia service=mongodb count=3
INFO[10-21|22:07:11] getting sirenia status                   fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] getting service metadata                 fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] getting primary job info                 fn=FixSirenia service=mongodb job.id=exoflynn03-db634360-e66f-47e8-953c-5ebefed628af
INFO[10-21|22:07:25] getting sync job info                    fn=FixSirenia service=mongodb job.id=exoflynn01-bdf389e5-3c0c-4e0b-bde7-6f721a27034c
INFO[10-21|22:07:25] terminating unassigned sirenia instances fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] starting sync job                        fn=FixSirenia service=mongodb job.id=exoflynn01-5c3ca0a6-c901-4c9e-964b-7575985f1737
INFO[10-21|22:07:26] waiting for instance to start            fn=FixSirenia service=mongodb job.id=exoflynn01-5c3ca0a6-c901-4c9e-964b-7575985f1737
INFO[10-21|22:07:26] waiting for cluster to come up read-write fn=FixSirenia service=mongodb
22:12:46.674138 host.go:157: timeout waiting for expected status
```

### LINKED ISSUE #3572: When a single-node cluster reboots, mongo vanishes
Similarly to https://github.com/flynn/flynn/issues/3552 my MongoDB dies when I restart a single node cluster. I've an app requiring MongoDB and would really love to continue using Flynn. 
However, I think a node should withstand a reboot without having to rebuild the entire stack.

```flynn -a appname mongodb mongo``` results in the following:

``` MongoDB shell version: 3.2.10
connecting to: leader.mongodb.discoverd:27017/f1716ca9bbaa2ac8e3ced9c306f0226e
2016-10-25T06:15:32.412+0000 I NETWORK  [thread1] getaddrinfo("leader.mongodb.discoverd") failed: Name or service not known
2016-10-25T06:15:32.420+0000 E QUERY    [thread1] Error: couldn't initialize connection to host leader.mongodb.discoverd, address is invalid :
connect@src/mongo/shell/mongo.js:231:14
@(connect):1:6```

This is the collect-debug-info gist from immediately after the reboot: https://gist.github.com/6d445d26b52847cfc5aac7950bc99a2b

I've tried applying flynn-host fix -n 1. Unfortunately, some segmentation violation occurs upon that process:

```
root@ubuntu-2gb-fra1-01:~# flynn-host fix -n 1
INFO[10-25|06:18:59] found expected hosts                     n=1
INFO[10-25|06:18:59] ensuring discoverd is running on all hosts
INFO[10-25|06:19:00] checking flannel
INFO[10-25|06:19:00] flannel looks good
INFO[10-25|06:19:00] waiting for discoverd to be available
INFO[10-25|06:19:00] checking for running controller API
INFO[10-25|06:19:00] found running controller API instances   n=1
INFO[10-25|06:19:00] found controller instance, checking critical formations
INFO[10-25|06:19:00] checking status of sirenia databases
INFO[10-25|06:19:00] checking for database state              db=postgres
INFO[10-25|06:19:00] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[10-25|06:19:00] found running leader                     fn=FixSirenia service=postgres
INFO[10-25|06:19:00] found running instances                  fn=FixSirenia service=postgres count=1
INFO[10-25|06:19:00] getting sirenia status                   fn=FixSirenia service=postgres
INFO[10-25|06:19:00] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[10-25|06:19:00] checking for database state              db=mariadb
INFO[10-25|06:19:00] skipping recovery of db, no state in discoverd db=mariadb
INFO[10-25|06:19:00] checking for database state              db=mongodb
INFO[10-25|06:19:00] checking sirenia cluster status          fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] no running leader                        fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] found running instances                  fn=FixSirenia service=mongodb count=3
INFO[10-25|06:19:00] getting sirenia status                   fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] getting service metadata                 fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] getting primary job info                 fn=FixSirenia service=mongodb job.id=ubuntu2gbfra101-1b4397fc-163d-4a51-8523-f986dbab606b
INFO[10-25|06:19:00] terminating unassigned sirenia instances fn=FixSirenia service=mongodb
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x729021]

goroutine 1 [running]:
panic(0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420015410, 0x0, 0x0, 0x0, 0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/host/fixer.(*ClusterFixer).FixSirenia(0xc42016ec90, 0xbeb8ce, 0x7, 0x0, 0x2)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/fixer/sirenia.go:111 +0xbe1
github.com/flynn/flynn/host/fixer.(*ClusterFixer).Run(0xc42016ec90, 0xc42028b060, 0xc42028b0c0, 0x0, 0xc42028b0c0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/fixer/fixer.go:122 +0x1089
github.com/flynn/flynn/host/fixer.(*ClusterFixer).Run-fm(0xc42028b060, 0xc42028b0c0, 0xc4200d7170, 0x3)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/cli/fix.go:8 +0x3e
github.com/flynn/flynn/host/cli.Run(0x7ffc633898cf, 0x3, 0xc420209ba0, 0x2, 0x2, 0xc4201d7c01, 0xc68ce8)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/cli/cli.go:57 +0x3ca
main.main()
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/host.go:149 +0x4d4
```


And this is the collect-debug-info gist AFTER I've tried to use ```flynn-host fix``` command: 
https://gist.github.com/4d8089d8eaed06dafd7643a0ef1a40c0

Maybe this helps to identify the issue? I've been able to reproduce it on my local VMWare machine and DigitalOcean instances...

In that other ticket, one reply states 

> I think I have identified the issue. It seems that there is a bug in the MongoDB appliance which >is only hit when both of the existing Sync and Primary peers go down and when resurrected >have different IP addresses.
>
>Thanks for reporting!

Which is also the same case here, if I am not mistaking?

### PR DESCRIPTION
**Pull request by josephglanville**
Misc fixes to the the cluster fixer/resurrection code for MongoDB.

Fixes #3572
Fixes #3552

### CODE REVIEW

File: appliance/mongodb/process.go [hunk 1]
```diff
@@ -437,8 +440,15 @@ func replSetGetStatusQuery(session *mgo.Session) (*replSetStatus, error) {
 func (p *Process) isReplInitialised() (bool, error) {
 	_, err := p.replSetGetStatus()
 	if err != nil {
-		if merr, ok := err.(*mgo.QueryError); ok && merr.Code == 94 {
-			return false, nil
+		if merr, ok := err.(*mgo.QueryError); ok {
+			switch merr.Code {
+			case 93:
+				return true, nil
+			case 94:
```
Comment (titanous) [inline appliance/mongodb/process.go]: Add comments explaining the error codes.
