### PR TITLE
Various Scheduler Fixes

### LINKED ISSUE #3274: scheduler logical race results in empty job state field and debug hang
I believe there is a logical race that resulted in this sequence of events:

1. The scheduler requests a job and then immediately decides to stop the job.
1. On the host this looks like a job stop (response: unknown job) followed by a job add (response: ratelimited)

    ```text
t=2016-08-11T05:40:37-0400 lvl=info msg="request started" req_id=f4a630db-3109-4de6-b460-1162eee2ee42 component=host method=DELETE path=/host/jobs/brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3 client_ip=192.168.200.12
t=2016-08-11T05:40:37-0400 lvl=info msg="acquiring state database" app=host pid=1476 host.id=brlrh01 fn=StopJob job.id=brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3
t=2016-08-11T05:40:37-0400 lvl=warn msg="job not found" app=host pid=1476 host.id=brlrh01 fn=StopJob job.id=brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3
t=2016-08-11T05:40:37-0400 lvl=info msg="request started" component=host req_id=d05fdf48-1049-423e-9c53-df01218acfd4 method=PUT path=/host/jobs/brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3 client_ip=192.168.200.12
t=2016-08-11T05:40:37-0400 lvl=warn msg="maximum concurrent AddJob calls running" app=host pid=1476 host.id=brlrh01 fn=AddJob job.id=brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3
t=2016-08-11T05:40:37-0400 lvl=info msg="request completed" component=host req_id=d05fdf48-1049-423e-9c53-df01218acfd4 status=429 duration=223.248µs
```
1. From this point on, the internal job state in the scheduler appears to be corrupt. The scheduler tries to persist it with an empty `state` field:

    ```text
lvl=eror msg="error persisting job" component=scheduler fn=RunPutJobs job.id=brlrh01-4a98c2f1-3c72-44c8-a302-95db233530c3 job.state= err="unknown_error: Something went wrong"
```
    Which the controller correctly rejects:

    ```text
lvl=info msg="request started" req_id=036eb533-c48e-488d-ad4c-c182ac39ed93 component=controller method=PUT path=/apps/fd94a84f-0b11-4cb9-8660-6fdb7af323f9/jobs/4a98c2f1-3c72-44c8-a302-95db233530c3 client_ip=100.100.88.60
lvl=eror msg="ERROR: insert or update on table \"job_cache\" violates foreign key constraint \"job_state_fkey\" (SQLSTATE 23503)" req_id=036eb533-c48e-488d-ad4c-c182ac39ed93 component=controller
lvl=info msg="request completed" req_id=036eb533-c48e-488d-ad4c-c182ac39ed93 component=controller status=500 duration=1.102444ms
```

1. I'm not sure if this is the same issue, but I'm going to assume it is. All requests for the scheduler debug state were hanging, the full goroutine trace is here: https://gist.github.com/cromulus/ed2a8a33940329c1392cf940e6ffb4d7

Thanks to @cromulus for reporting this.

### LINKED ISSUE #3324: "flynn -a gitreceive env set" returns "timed out waiting for job events: map[app:map[up:2]]"
This happens repeatedly (looped in the init script) on a newly restored cluster. 

https://gist.github.com/f3b193a2096258fcc13ccd5d61386ff5

(Only one of the nodes was able to return collect-debug-info correctly, the other two hit 405s despite very similar log sizes of ~90MB).

### LINKED ISSUE #3326: Scheduler wasn't running properly after replacing a node
We had a cluster where a node died. Shortly after its replacement came online, the scheduler stopped running. Then it stopped running on all the other hosts.

Here's a Gist with debug info from one of the hosts:
https://gist.github.com/85f28835546bdba808681933644b3236

And tarballs for the others:
https://bazaarvoice.box.com/s/972dnf2p692m40rwwvn6kks3ear0ihfr
https://bazaarvoice.box.com/s/cl983chbpg6v6m0l86fx9vq63gzch5hv
https://bazaarvoice.box.com/s/fvm5sukewaf82kmp7uz6ujkm5mnteeqo
https://bazaarvoice.box.com/s/xsaf06vwnuma1uziimnafcqal7l4vblk

### PR DESCRIPTION
**Pull request by lmars**
See inline comments / commit messages for details.

Closes #3274
Closes #3324
Closes #3326

### CODE REVIEW

File: controller/scheduler/scheduler.go [hunk 1]
```diff
@@ -837,19 +845,71 @@ func (s *Scheduler) ShuffledHosts() []*Host {
...
+			queue[job.UUID] = append(queue[job.UUID], job)
+
+			// if there is only one job in the queue, persist it
+			if len(queue[job.UUID]) == 1 {
+				go persist(job)
+			}
+		case uuid := <-done:
+			// pop a job from the front of the queue
+			queue[uuid] = queue[uuid][1:]
+
```
Comment (titanous) [inline controller/scheduler/scheduler.go]: Should this delete from the map if the queue length is empty? Otherwise I think it will leak memory.

Comment (titanous) [inline controller/scheduler/scheduler.go]: Also, where is this popped job used?

Comment (lmars) [inline controller/scheduler/scheduler.go]: Updated to delete from the map in 085928d.

The popped job is the one that just got persisted, it needs to stay in the queue until it is persisted so that other jobs get queued behind it. Does that make sense? Maybe I should update the comment to "remove the persisted job from the queue"?

Comment (titanous) [inline controller/scheduler/scheduler.go]: Yeah, a comment update would be great.

**Comment by lmars** [comment]
@titanous comments addressed

File: controller/scheduler/scheduler.go [hunk 2]
```diff
@@ -837,19 +845,73 @@ func (s *Scheduler) ShuffledHosts() []*Host {
...
+	// given UUID, and the loop below persists the jobs in the slice
+	// in FIFO order
+	queue := make(map[string][]*ct.Job)
+
+	// done is a channel which receives a UUID once a job has been
+	// persisted for that UUID, thus potentially triggering the
+	// persistence of the next job in the queue for that UUID
+	done := make(chan string)
+
+	// persist makes multiple attemtps to persist the given job, sending to
```
Comment (titanous) [inline controller/scheduler/scheduler.go]: attempts

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM
