### PR TITLE
host: Retry creating AUFS mounts

### LINKED ISSUE #2044: host: Error creating AUFS mount
Twice now has my Flynn cluster failed to run Redis based on this gist:
https://gist.github.com/lmars/fca0f18b4ecd507fb39a

Only way to recover from it, really, is by re-creating the cluster and trying again.

Gist of the flynn-host error:
https://gist.github.com/rikur/ac413fd781722315517f
Csysdig output during the failure:
https://gist.github.com/rikur/b147ab31327b83da608b

### PR DESCRIPTION
**Pull request by lmars**
Verified this works by booting a cluster, seeing the `EINVAL` in sysdig, but observing that the job still started, see the host log:

```
now=2015-12-10T00:54:35+0000 at=read_config fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 at=checkout
time="2015-12-10T00:54:35Z" level="error" msg="Couldn't run auplink before unmount: exit status 22" 
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 at=mount
now=2015-12-10T00:54:35+0000 at=write_config fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 at=define_domain
...
now=2015-12-10T00:54:41+0000 fn=watch_container job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc at=change state=running
now=2015-12-10T00:54:41+0000 fn=watch_container job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc at=running
```

Fixes #2044

### CODE REVIEW

File: host/libvirt_lxc_backend.go [hunk 1]
```diff
@@ -394,7 +403,13 @@ func (l *LibvirtLXCBackend) Run(job *host.Job, runConfig *RunConfig) (err error)
 	}
 
 	g.Log(grohl.Data{"at": "checkout"})
-	rootPath, err := l.pinkerton.Checkout(job.ID, imageID)
+	var rootPath string
+	// creating an AUFS mount can fail intermittently with EINVAL, so try a
+	// few times (see https://github.com/flynn/flynn/issues/2044)
+	err = aufsMountAttempts.Run(func() (err error) {
+		rootPath, err = l.pinkerton.Checkout(job.ID, imageID)
```
Comment (titanous) [inline host/libvirt_lxc_backend.go]: Does it make sense to scope this retry to just the EINVAL error?

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM
