### PR TITLE
Scheduler Updates

### LINKED ISSUE #1922: scheduler: Cancel in-flight crash restarts before stopping running jobs
Currently, when a formation is scaled down, we attempt to stop jobs in that formation. However, if there are any pending job restart timers active due to crashed jobs, we can end up in a situation where there are no jobs available to stop for a formation, making the scheduler unable to do its job.

When a job stop request is received, before of attempting to stop a job, cancel pending crash restarts first.

### LINKED ISSUE #2004: scheduler nukes everything if host is unregistered
A single-node cluster run by @temujin9 suffered an (as yet unexplained) hiccup where the `flynn-host` service instance was temporarily expired in discoverd.

The scheduler saw this and decided it'd be a great time to kill everything, including postgres:

```
t=2015-10-21T17:35:36+0000 lvl=info msg="handling host event" component=scheduler fn=HandleHostEvent event.type=down
t=2015-10-21T17:35:36+0000 lvl=info msg="host is down, stopping job event stream" component=scheduler fn=HandleHostEvent event.type=down host.id=ip1010046117
t=2015-10-21T17:35:36+0000 lvl=info msg="unfollowing host" component=scheduler fn=unfollowHost host.id=ip1010046117
t=2015-10-21T17:35:36+0000 lvl=info msg="removing job" component=scheduler fn=unfollowHost host.id=ip1010046117 job.id=ip1010046117-9b7af9a9-67cd-499b-8abd-e8c9427c07f2
t=2015-10-21T17:35:36+0000 lvl=info msg="triggering rectify" component=scheduler key="{AppID:5cfa0f99-e32f-4d08-987c-3b0572118cc1 ReleaseID:aef8635a-f956-42f0-aec2-3c42619f88e3}"
t=2015-10-21T17:35:36+0000 lvl=info msg="removing job" component=scheduler fn=unfollowHost host.id=ip1010046117 job.id=ip1010046117-6db3a55a-9e89-4eff-b4e8-3d36e880cce3
t=2015-10-21T17:35:36+0000 lvl=info msg="triggering rectify" component=scheduler key="{AppID:ff8d2703-448d-42cf-addc-b6e738e0f349 ReleaseID:de86f3ca-4da2-40a5-95d7-f994e25a6f05}"
...
```

https://gist.github.com/temujin9/bc52b9f648ca2e13dc77#file-gistfile1-txt-L548-L550

I haven't looked at why the scheduler did this yet, but it doesn't seem like the correct behavior.

Cluster debug info: https://gist.github.com/80a36e8c54d49b6123e1

### LINKED ISSUE #2013: scheduler: Type-less jobs always considered new
When a cluster has active jobs without a type, they are treated as new each time `SyncJobs` runs (so every 30s), meaning they are continually logged / persisted to the controller:

```
t=2015-10-22T12:15:57+0000 lvl=info msg="syncing jobs" component=scheduler fn=SyncJobs
t=2015-10-22T12:15:57+0000 lvl=info msg="getting host list" component=scheduler fn=SyncJobs
t=2015-10-22T12:15:57+0000 lvl=info msg="getting jobs for host bronto.default.ahardwick.uk0.bigv.io" component=scheduler fn=SyncJobs host.id=bronto.default.ahardwick.uk0.bigv.io
t=2015-10-22T12:15:57+0000 lvl=info msg="got 56 active job(s) for host bronto.default.ahardwick.uk0.bigv.io" component=scheduler fn=SyncJobs host.id=bronto.default.ahardwick.uk0.bigv.io
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type= job.status=crashed
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 app.name=ankylo release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type= job.status=done
t=2015-10-22T12:15:57+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 job.state=down
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d job.state=down
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 job.state=down
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef job.state=down
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 job.state=crashed
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 job.state=down
t=2015-10-22T12:15:57+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 job.state=down
...
t=2015-10-22T12:16:27+0000 lvl=info msg="syncing jobs" component=scheduler fn=SyncJobs
t=2015-10-22T12:16:27+0000 lvl=info msg="getting host list" component=scheduler fn=SyncJobs
t=2015-10-22T12:16:27+0000 lvl=info msg="getting jobs for host bronto.default.ahardwick.uk0.bigv.io" component=scheduler fn=SyncJobs host.id=bronto.default.ahardwick.uk0.bigv.io
t=2015-10-22T12:16:27+0000 lvl=info msg="got 56 active job(s) for host bronto.default.ahardwick.uk0.bigv.io" component=scheduler fn=SyncJobs host.id=bronto.default.ahardwick.uk0.bigv.io
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=4135d4ba-0710-427b-93b7-592a5f2b4f2d job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=d16af545-0d53-472a-96b3-842676e10a8a job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 app.name=ankylo release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 app.id=1fc3a0b1-d0d9-4d32-84f7-474bb23fe093 release.id=bcc0ea51-cf68-4f45-95e8-fd316c1401c0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=acf2b980-6725-4f2d-8f9a-70514b1d54ad job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=e35edb0a-0b25-46b4-995a-faf47beb67c7 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type= job.status=done
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=718089be-7b25-4121-8655-c0c3f267f891 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="creating new job" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="looking up formation" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="queuing job for persistence" component=scheduler fn=SaveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 app.name=stegosaurus release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type= job.status=crashed
t=2015-10-22T12:16:27+0000 lvl=info msg="saved job to controller" component=scheduler fn=handleActiveJob job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 app.id=d9b319db-9d63-44d3-9c20-892208d983c5 release.id=1324f209-841f-4685-8e8c-8a89955dc5e0 job.type=
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-02239f27-d6cc-4eee-88ae-37112f5c9687 job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-be00b2ee-012d-4318-8471-018cb9b1c88d job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-5cb9193f-b6a0-4c57-ae35-1826932778f4 job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-33624495-aa94-4985-8235-e8239d03b932 job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-4481a5a3-2544-4751-8ff7-2f302586a7c8 job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-cc5cc8f6-5ca9-45aa-a269-c4c7f25fefef job.state=down
t=2015-10-22T12:16:27+0000 lvl=info msg="persisting job" component=scheduler fn=RunPutJobs job.id=bronto.default.ahardwick.uk0.bigv.io-d49398d2-f215-42a0-9a2b-96fd6e933bc8 job.state=crashed

### LINKED ISSUE #2030: non-leader schedulers attempt to handle "crashed" jobs
[This code](https://github.com/flynn/flynn/blob/dc83867a0fccbf07f744734f5737bf4dedca1ad1/controller/scheduler/scheduler.go#L952-L960)  appears to be wrong. It is run no matter if the scheduler is a leader or not, so it doesn't know if the job is supposed to be stopping (for instance it might not have an updated formation yet that the leader is reacting to).

It's possible that I'm missing something about how this is supposed to work, but it looks wrong to me.

### LINKED ISSUE #2133: scheduler: Failing jobs continue to be retried after scale down
See the repeated retry of the failed worker job in [this CI failure](https://ci.flynn.io/builds/20151115010657-73c9f645) (the failing worker is created in [this test](https://github.com/flynn/flynn/blob/master/test/test_scheduler.go#L375-L379)).

### PR DESCRIPTION
**Pull request by lmars**
Apologies for the big diff with lots of small changes, but it was hard to split these up and still have the tests pass.

To summarise:

* Add `Job.InternalID`, distinct from `Job.JobID`, making jobs easier to track (see [this comment](https://github.com/flynn/flynn/blob/scheduler-updates/controller/scheduler/job.go#L44-L49))
* Reduce logging
* Support getting only "active" formations from the controller (i.e. ones with at least one process scaled up) so the scheduler only needs to make a single request in `SyncFormations` (rather than getting all apps, then a request per app for formations)
* Support getting expanded formations from the controller to avoid the scheduler needing to lookup apps / releases / artifacts separately
* Start jobs in a goroutine (part of fixing #1920), using "placement requests" to the main loop to determine which host to start the job on at each attempt
* Refactor handling of job events & comment to make it much clearer
* Replace `JobStateCrashed` with `JobStateScheduled` to indicate the job is scheduled to start in the future
* Add a job restart timer so restarts can be cancelled before trying to stop running jobs (fixes #1922)
* Jobs with a type not from the release (e.g. slugbuilder jobs) don't trigger a rectify
* Track failed formation lookups and trigger a rectify if the formation appears in a future sync
* Track type-less jobs in memory (fixes #2013)
* Don't handle crashed jobs in non-leaders (fixes #2030)
* Cancel new jobs (i.e. ones in the process of being started) when stopping jobs so they do not continue to be started (fixes #2133, fixes #2004)

### CODE REVIEW

File: controller/controller.go [hunk 1]
```diff
@@ -255,6 +255,7 @@ func appHandler(c handlerConfig) http.Handler {
 	httpRouter.DELETE("/apps/:apps_id/formations/:releases_id", httphelper.WrapHandler(api.appLookup(api.DeleteFormation)))
 	httpRouter.GET("/apps/:apps_id/formations", httphelper.WrapHandler(api.appLookup(api.ListFormations)))
 	httpRouter.GET("/formations", httphelper.WrapHandler(api.GetFormations))
+	httpRouter.GET("/formations/active", httphelper.WrapHandler(api.ListActiveFormations))
```
Comment (titanous) [inline controller/controller.go]: What do you think about making this a URL query parameter like `/formations?active=true` or `/formations?status=active`?

File: controller/scheduler/job.go [hunk 2]
```diff
@@ -9,80 +8,106 @@ import (
...
-
+// Job is an in-memory representation of a cluster job
 type Job struct {
+	// InternalID is used to track jobs in-memory and is added to the
+	// cluster job's metadata (with key "flynn-controller.scheduler_id").
+	//
+	// It is distinct from the cluster job's ID due to the fact that a
+	// cluster job only has an ID once a host has been picked to run the
+	// job on, and we need to track it before that happens.
+	InternalID string
```
Comment (titanous) [inline controller/scheduler/job.go]: Can we just populate this with the job ID with the host ID stripped?

**Comment by titanous** [comment]
Can any tests be added for fixed bugs?

**Comment by lmars** [comment]
@titanous comments addressed (I added test coverage around picking which jobs to stop)

File: controller/scheduler/job.go [hunk 3]
```diff
@@ -96,27 +121,26 @@ func (j *Job) IsSchedulable() bool {
...
-			formTypeJobs = append(formTypeJobs, j)
+func (j Jobs) WithFormationAndType(f *Formation, typ string) []*Job {
+	jobs := make([]*Job, 0, len(j))
+	for _, job := range j {
+		if job.Formation == f && job.Type == typ {
+			jobs = append(jobs, job)
 		}
 	}
-	return formTypeJobs
+	return jobs
```
Comment (titanous) [inline controller/scheduler/job.go]: This should be sorted for determinism.

File: controller/scheduler/scheduler.go [hunk 4]
```diff
@@ -821,153 +965,82 @@ func (s *Scheduler) triggerRectify(key utils.FormationKey) {
...
-	var host *Host
-	for id, h := range s.hosts {
-		count, ok := counts[id]
-		if !ok || count < minCount {
-			minCount = count
-			host = h
+	// determine the most recent job
+	job := runningJobs[0]
+	for _, j := range runningJobs {
+		if j.startedAt.After(job.startedAt) {
```
Comment (titanous) [inline controller/scheduler/scheduler.go]: If the `WithFormationAndType` method sorts, this sort shouldn't be necessary.

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM!
