### PR TITLE
Fix bootstrapping from older backups

### LINKED ISSUE #2988: Status Page on the Dashboard not working due to an HTTP 401
Hi,
I just upgraded to the new stable version v20160624.1 and the status page of the dashboard refuses to work due to an HTTP 401 to the status endpoint. Have a look:
screen shot 2016-06-25 at 12 51 53

### LINKED ISSUE #3198: Restoring from backup pre-mongo doesn't create mongodb provider
Restoring from a backup pre-dating the mongodb appliance causes it not to be there. This in turn breaks database related views in the dashboard.

Thank you @swaits for reporting this.

### PR DESCRIPTION
**Pull request by jvatic**
- Ensures that MariaDB, MongoDB, and docker-receive are deployed,
and that STATUS_KEY is set in the dashboard
- Add mongodb to status app

<del>This isn't ready to merge just yet as MariaDB isn't healthy when it scales up. @josephglanville any input you can provide here would be appreciated.</del>
<br/>

Closes #3198
Closes #2988

### CODE REVIEW

File: bootstrap/bootstrap.go [hunk 1]
```diff
@@ -184,17 +184,11 @@ func (m Manifest) RunWithState(ch chan<- *StepInfo, state *State) (*State, error
...
 	var manifest Manifest
 	var steps []json.RawMessage
 	if err := json.Unmarshal(manifestData, &steps); err != nil {
-		return err
-	}
-
-	cfg.Singleton = cfg.MinHosts == 1
-	if s := os.Getenv("SINGLETON"); s != "" {
-		cfg.Singleton = s == "true"
+		return manifest, err
```
Comment (lmars) [inline bootstrap/bootstrap.go]: Should these error returns not be `return nil, err`?

File: host/cli/bootstrap.go [hunk 2]
```diff
@@ -223,6 +225,17 @@ $function$;
...
+	manifestStepMap := make(map[string]bootstrap.Step, len(manifestSteps))
+	{
+		steps, err := bootstrap.UnmarshalManifest(manifest, nil)
+		if err != nil {
+			return fmt.Errorf("error decoding manifest json: %s", err)
+		}
+		for _, step := range steps {
+			manifestStepMap[step.StepMeta.ID] = step
+		}
+	}
```
Comment (lmars) [inline host/cli/bootstrap.go]: Why the braces?

File: host/cli/bootstrap.go [hunk 3]
```diff
@@ -549,6 +603,36 @@ WHERE release_id = (SELECT release_id FROM apps WHERE name = 'discoverd')
...
+					PrivateKey: r.Certificate.Key,
+				}
+				break
+			}
+		}
+		dockerReceiveRouteStep := manifestStepMap["docker-receive-route"]
+		steps := bootstrap.Manifest{
+			manifestStepMap["docker-receive-secret"],
+			manifestStepMap["docker-receive"],
+			dockerReceiveRouteStep,
```
Comment (lmars) [inline host/cli/bootstrap.go]: Does this need to be in a variable?

File: host/cli/bootstrap.go [hunk 4]
```diff
@@ -504,11 +530,37 @@ WHERE release_id = (SELECT release_id FROM apps WHERE name = 'discoverd')
...
-	// get blobstore config
-	client, err := controller.NewClient("http://"+controllerInstances[0].Addr, data.Controller.Release.Env["AUTH_KEY"])
+	controllerKey := data.Controller.Release.Env["AUTH_KEY"]
+	state.SetControllerKey(controllerKey)
+	state.StepData["controller-key"] = &bootstrap.RandomData{controllerKey}
+	if shouldDeployMariaDB {
+		steps := bootstrap.Manifest{
+			manifestStepMap["mariadb-password"],
+			manifestStepMap["mariadb"],
+			manifestStepMap["add-mysql-provider"],
```
Comment (josephglanville) [inline host/cli/bootstrap.go]: Might want to add the `mariadb-wait` step here.

File: host/cli/bootstrap.go [hunk 5]
```diff
@@ -504,11 +530,37 @@ WHERE release_id = (SELECT release_id FROM apps WHERE name = 'discoverd')
...
+		if _, err := steps.RunWithState(ch, state); err != nil {
+			return fmt.Errorf("error deploying mariadb: %s", err)
+		}
+	}
+
+	if shouldDeployMongoDB {
+		steps := bootstrap.Manifest{
+			manifestStepMap["mongodb-password"],
+			manifestStepMap["mongodb"],
+			manifestStepMap["add-mongodb-provider"],
```
Comment (josephglanville) [inline host/cli/bootstrap.go]: As above, probably want the `mongodb-wait` step.

File: host/cli/bootstrap.go (hunk 4 above)
Comment (jvatic) [inline host/cli/bootstrap.go]: Done.

File: host/cli/bootstrap.go (hunk 5 above)
Comment (jvatic) [inline host/cli/bootstrap.go]: Done.

**Comment by jvatic** [comment]
@lmars @josephglanville comments addressed and both databases are now working as expected (I think my vagrant box being out of date was causing the mariadb issue).

One remaining issue is the mongodb status never shows up as healthy (both with clean bootstrap and from backup). I may just move that into another PR if it's not any easy fix.

**Comment by jvatic** [comment]
The mongodb unhealthy status isn't due incorrect configuration in the status app as I thought it might have been.

**Comment by titanous** [comment]
@jvatic Does mongodb become healthy after running `flynn resource add mongodb`?

**Comment by jvatic** [comment]
@titanous Nope.

**Comment by titanous** [comment]
Okay, please post the logs.

**Comment by jvatic** [comment]
https://gist.github.com/e3e735c07dfdfee9327a445348457d9a

**Comment by jvatic** [comment]
I've reproduced the mongodb status issue on the latest stable release: #3316

**Comment by jvatic** [comment]
I can confirm #3317 fixes the mongodb status issue (#3316).

**Comment by titanous** [comment]
Since we now have a way of testing backup restores, does it make sense to add some tests? /cc @lmars

**Comment by jvatic** [comment]
Yeah, seems like a good idea

**Comment by jvatic** [comment]
Haven't tested the test yet (0fcc251)

File: script/generate-backups [hunk 6]
```diff
@@ -65,6 +65,16 @@ main() {
...
   done
+
+  # generate backup without MySQL and MongoDB, and with STATUS_KEY missing from the dashboard
+  local version="v20160814.0"
+  bootstrap_cluster "${version}"
+  git_deploy_app
+  add_redis_resource
+  remove_mysql
+  remove_mongodb
+  remove_dashboard_status_key
```
Comment (lmars) [inline script/generate-backups]: Rather than modifying the latest release, we should use a version where these cases were true.

Version `v20160309.0` (included above) satisfies all of these cases (MariaDB was added in `v20160311.1`, MongoDB in `v20160706.0` and dashboard `STATUS_KEY` in `v20160620.1`).

File: test/test_zz_backup.go [hunk 7]
```diff
@@ -159,4 +160,18 @@ func (s *ZZBackupSuite) testClusterBackup(t *c.C, index int, path string) {
 	})
 	t.Assert(err, c.IsNil)
 	t.Assert(redisResult, SuccessfulOutputContains, "PONG")
+
+	if strings.HasSuffix(filepath.Base(path), "missing-dbs-and-dashboard-status.tar") {
```
Comment (lmars) [inline test/test_zz_backup.go]: We should do these checks for all the backups.

File: vendor/github.com/graphql-go/graphql [hunk 8]
```diff
@@ -0,0 +1 @@
+Subproject commit 1d9282bf75ff1bb4518590536ef930d22fab83e8
```
Comment (lmars) [inline vendor/github.com/graphql-go/graphql]: Drop this change

**Comment by lmars** [comment]
FYI I have added d9ef584 which fixes the fact that changes to in-memory releases is not reflected in the database and could lead to unexpected issues in the future.

**Comment by titanous** [comment]
There appears to be a bug in this:

```text
14:10:28.928004 deploy-app mariadb error: object_exists: application "mariadb" already exists
14:10:28.928062 host.go:154: error deploying mariadb: object_exists: application "mariadb" already exists
```

When trying to restore a backup that was taken from a cluster with the mariadb app but not scaled up (the default configuration) so no database dump was not stored in the backup.

**Comment by lmars** [comment]
I've pushed some more changes to fix the mariadb app existence and to also add tests for mysql / mongodb backups.

Unfortunately mysql restores seem to be broken:

```
++ 15:57:25.175 checking mysql resource
++ 15:57:25.175 /home/ubuntu/go/src/github.com/flynn/flynn/cli/bin/flynn mysql console -- -e SELECT * FROM foos
ERROR 1045 (28000): Access denied for user '0dba71ca1b751a3a96f2da7c4f492c16'@'100.101.100.22' (using password: YES)
```

This seems to be broken on master, you can verify by running:

```
$ script/bootstrap-flynn --from-backup https://s3.amazonaws.com/flynn-test/backups/cluster/v20160814.0-nodejs-mysql.tar
```

and then trying to get a console:

```
$ flynn -a nodejs mysql console
ERROR 1045 (28000): Access denied for user '0dba71ca1b751a3a96f2da7c4f492c16'@'100.100.88.22' (using password: YES)
```

For now I am not putting the mysql backup on the CI machine (so the tests will pass), but we need to fix this.
