### PR TITLE
cli: Update local cluster config after successful domain migration

### LINKED ISSUE #2453: flynn cluster migrate-domain doesn't update .flynnrc
Using latest release, migrate-domain is leaving clusters in a partially broken state where the dashboard works, but the CLI does not work because the controller is not updated to the new domain, i.e. does not have a new certificate, and the .flynnrc file is not updated. Everything else appears fine (e.g. git and dashboard are updated with new domain/certificate).

Also, it is spits out an error message, but continues:

```
Migrate cluster domain from "xxxx.flynnhub.com" to "domain.com"? (yes/no): yes
Migrating cluster domain (this can take up to 2m0s)...
Get http://router-api.discoverd:5000/routes: dial tcp: lookup router-api.discoverd: no such host
Changed cluster domain from "xxxx.flynnhub.com" to "domain.com"
```

Logs: https://gist.github.com/b8de3045c2c7527bd495

### PR DESCRIPTION
**Pull request by jvatic**
Closes #2453

### CODE REVIEW

**Comment by jvatic** [comment]
We should have an integration test for domain migration via the cli.

File: cli/cluster.go [hunk 1]
```diff
@@ -288,7 +292,32 @@ func runClusterMigrateDomain(args *docopt.Args) error {
...
+				defer caFile.Close()
+				if _, err := caFile.Write([]byte(dm.TLSCert.CACert)); err != nil {
+					return err
+				}
+				if err := cfg.WriteGlobalGitConfig(cluster.GitURL, caFile.Name()); err != nil {
+					return err
+				}
+				cfg.RemoveGlobalGitConfig(fmt.Sprintf("https://git.%s", dm.OldDomain))
+
+				fmt.Println("CLI updated locally")
```
Comment (titanous) [inline cli/cluster.go]: `Updated local CLI configuration`

**Comment by titanous** [comment]
LGTM pending comment
