### PR TITLE
cli: Fix create command when not in a git repo

### LINKED ISSUE #1078: [flynn create] "exit status 128" on non-git-initialized path.
Running `flynn create` from a path that isn't a git repository yields `exit status 128`.

Recommendation:

- Allow `flynn create` from a non-git initialized path. Or
- Provide a more descriptive error message.

### PR DESCRIPTION
**Pull request by lmars**
Fixes #1078

### CODE REVIEW

File: cli/git.go [hunk 1]
```diff
@@ -13,6 +13,10 @@ import (
 	cfg "github.com/flynn/flynn/cli/config"
 )
 
+func inGitRepo() bool {
+	return exec.Command("git", "rev-parse", "--git-dir").Run() == nil
```
Comment (titanous) [inline cli/git.go]: Should we memoize this? If we don't we'll exec multiple times in a single command run.

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM
