### PR TITLE
controller: avoid panic when streaming formation updates

### LINKED ISSUE #2175: controller: Panic subscribing to formation updates
In https://gist.github.com/anonymous/5e7cc17cc6c01953f907, job `controller-web-flynn1448137186-aa89fd57-4f8d-4733-b41e-5fe20ce65266` crashed with the following panic:

```
panic: send on closed channel

goroutine 199 [running]:
main.(*FormationRepo).sendUpdatedSince(0xc208163630, 0xc20811f8c0, 0xc20811f920, 0xecde2cf69, 0x0, 0xa30320, 0x0, 0x0)
	/tmp/tmp.Q2hgRVCoYK/src/github.com/flynn/flynn/controller/formation.go:284 +0x385
created by main.(*FormationRepo).Subscribe
	/tmp/tmp.Q2hgRVCoYK/src/github.com/flynn/flynn/controller/formation.go:265 +0x16c
```

### PR DESCRIPTION
**Pull request by imjorge**
Closes #2175

### CODE REVIEW

**Comment by imjorge** [comment]
The test uses a `time.Sleep` which is fragile.

File: controller/formation.go [hunk 1]
```diff
@@ -303,7 +318,14 @@ func (r *FormationRepo) unsubscribeLocked(ch chan *ct.ExpandedFormation) {
 		for range ch {
 		}
 	}()
+	si, ok := r.subscriptions[ch]
 	delete(r.subscriptions, ch)
+	if ok {
+		si.uc <- struct{}{}
+		si.wg.Wait()
```
Comment (lmars) [inline controller/formation.go]: We want the `sendUpdatedSince` goroutine to stop if the channel is closed, which we can do by just wrapping the channel:

```go
type FormationSubscription struct {
	mtx sync.Mutex
	ch  chan *ct.ExpandedFormation
}

func (f *FormationSubscription) Notify(ef *ct.ExpandedFormation) bool {
	f.mtx.RLock()
	defer f.mtx.RUnlock()
	if f.ch == nil {
		return false
	}
	f.ch <- ef
	return true
}

func (f *FormationSubscription) Close() {
	f.mtx.Lock()
	defer f.mtx.Unlock()
	close(f.ch)
	f.ch = nil
}

// in sendUpdatedSince
for rows.Next() {
	// ...
	if ok := f.Notify(ef); !ok {
		return nil
	}
}
```

WDYT?

Comment (imjorge) [inline controller/formation.go]: But that way we are not ALSO selecting on stopCh inside sendUpdatedSince. Right?

--jmf

Comment (imjorge) [inline controller/formation.go]: But that way we are **not ALSO selecting** on `stopCh` inside `sendUpdatedSince`. Right?

Comment (lmars) [inline controller/formation.go]: Correct, but `stopCh` gets closed [at the same time as unsubscribing](https://github.com/flynn/flynn/blob/master/controller/formation.go#L400-L401), so this will have the same effect (stopping the `sendUpdatedSince` goroutine when the channel is unsubscribed).

Comment (imjorge) [inline controller/formation.go]: So drop `stopCh` altogether?

Comment (lmars) [inline controller/formation.go]: I reckon so yes

File: controller/formation.go [hunk 2]
```diff
@@ -21,13 +21,35 @@ type formationKey struct {
...
+}
+
 type FormationRepo struct {
 	db        *postgres.DB
 	apps      *AppRepo
 	releases  *ReleaseRepo
 	artifacts *ArtifactRepo
 
-	subscriptions map[chan *ct.ExpandedFormation]struct{}
+	subscriptions map[chan *ct.ExpandedFormation]*formationSubscription
```
Comment (lmars) [inline controller/formation.go]: Make this `map[*formationSubscription]struct{}`

File: controller/formation.go [hunk 3]
```diff
@@ -243,11 +265,10 @@ func (r *FormationRepo) unsubscribeAll() {
 
 	for ch := range r.subscriptions {
 		r.unsubscribeLocked(ch)
-		close(ch)
 	}
 }
 
-func (r *FormationRepo) Subscribe(ch chan *ct.ExpandedFormation, stopCh <-chan struct{}, since time.Time) error {
+func (r *FormationRepo) Subscribe(ch chan *ct.ExpandedFormation, since time.Time, sendUpdateSinceDone chan<- struct{}) error {
```
Comment (lmars) [inline controller/formation.go]: Just call this argument `updatesDone`, or maybe even just `updated`

File: controller/formation.go [hunk 4]
```diff
@@ -260,13 +281,21 @@ func (r *FormationRepo) Subscribe(ch chan *ct.ExpandedFormation, stopCh <-chan s
...
+
+	go r.sendUpdatedSince(ch, f, since, sendUpdateSinceDone)
 	return nil
 }
 
-func (r *FormationRepo) sendUpdatedSince(ch chan *ct.ExpandedFormation, stopCh <-chan struct{}, since time.Time) error {
+func (r *FormationRepo) sendUpdatedSince(ch chan *ct.ExpandedFormation, f *formationSubscription, since time.Time, sendUpdatedSinceDone chan<- struct{}) error {
+	if sendUpdatedSinceDone != nil {
+		defer func() {
+			sendUpdatedSinceDone <- struct{}{}
```
Comment (lmars) [inline controller/formation.go]: Just close this channel

File: controller/formation.go [hunk 5]
```diff
@@ -21,13 +21,35 @@ type formationKey struct {
 	AppID, ReleaseID string
 }
 
+type formationSubscription struct {
```
Comment (lmars) [inline controller/formation.go]: We should add a comment as to why we are wrapping the channel like this

File: controller/formation.go (hunk 1 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go (hunk 2 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go (hunk 3 above)
Comment (imjorge) [inline controller/formation.go]: Done. Used `updated`.

File: controller/formation.go (hunk 4 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go (hunk 5 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go [hunk 6]
```diff
@@ -182,8 +208,10 @@ func (r *FormationRepo) publish(appID, releaseID string) {
 	r.subMtx.RLock()
 	defer r.subMtx.RUnlock()
 
-	for ch := range r.subscriptions {
-		ch <- f
+	for sub := range r.subscriptions {
+		if !sub.notify(f) {
+			break
```
Comment (lmars) [inline controller/formation.go]: We shouldn't break if one of the subscribers has gone away (the other subscribers may still be open)

File: controller/formation.go [hunk 7]
```diff
@@ -257,16 +284,24 @@ func (r *FormationRepo) Subscribe(ch chan *ct.ExpandedFormation, stopCh <-chan s
...
+	go r.sendUpdatedSince(sub, since, updated)
+	return sub, nil
 }
 
-func (r *FormationRepo) sendUpdatedSince(ch chan *ct.ExpandedFormation, stopCh <-chan struct{}, since time.Time) error {
+func (r *FormationRepo) sendUpdatedSince(sub *FormationSubscription, since time.Time, updated chan<- struct{}) error {
+	if updated != nil {
+		defer func() {
+			close(updated)
+		}()
```
Comment (lmars) [inline controller/formation.go]: `defer close(updated)`

File: controller/formation.go [hunk 8]
```diff
@@ -281,29 +316,31 @@ func (r *FormationRepo) sendUpdatedSince(ch chan *ct.ExpandedFormation, stopCh <
...
-func (r *FormationRepo) unsubscribeLocked(ch chan *ct.ExpandedFormation) {
-	go func() {
+func (r *FormationRepo) unsubscribeLocked(sub *FormationSubscription) {
+	go func(ch chan *ct.ExpandedFormation) {
 		// drain to prevent deadlock while removing the listener
 		for range ch {
 		}
-	}()
-	delete(r.subscriptions, ch)
+	}(sub.ch)
```
Comment (lmars) [inline controller/formation.go]: There is no need to pass the channel to the goroutine, the variable binding will not change.

File: controller/formation.go [hunk 9]
```diff
@@ -281,29 +316,31 @@ func (r *FormationRepo) sendUpdatedSince(ch chan *ct.ExpandedFormation, stopCh <
...
+	_, ok := r.subscriptions[sub]
+	delete(r.subscriptions, sub)
+	if ok {
+		sub.close()
```
Comment (lmars) [inline controller/formation.go]: No need to check if it is in `r.subscriptions`, just close it.

File: controller/formation.go (hunk 8 above)
Comment (imjorge) [inline controller/formation.go]: Actually it matters since `sub.ch` will become `nil` when the subscription is closed.

[This deadlocks](https://play.golang.org/p/3MRVr6j___).

[This does not dealock](https://play.golang.org/p/GADxvT3LZ5).

File: controller/formation.go (hunk 6 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go (hunk 7 above)
Comment (imjorge) [inline controller/formation.go]: Done.

File: controller/formation.go (hunk 9 above)
Comment (imjorge) [inline controller/formation.go]: Done. Protected `sub.close()` to be idempotent (do not panic on already closed channel).

File: controller/formation.go (hunk 8 above)
Comment (lmars) [inline controller/formation.go]: Ah yeh, ignore me :smile:

**Comment by titanous** [comment]
@imjorge looks like this needs a rebase.

**Comment by imjorge** [comment]
@titanous rebased.

**Comment by lmars** [comment]
LGTM

**Comment by josephglanville** [comment]
Appears to have introduced a hang (atleast in the controller unit tests)

**Comment by lmars** [comment]
See #2208 re the controller hang.
