### PR TITLE
test: include custom port on ci links

### LINKED ISSUE #821: Flynn CI running on a non-standard port renders incorrect links
The Flynn CI streaming build logs are currently hard coded to be `https://ci.flynn.io/...` (see [here](https://github.com/flynn/flynn/blob/master/test/runner/runner.go#L219)), but the runner could be running on a different port using the `--listen` flag.

### PR DESCRIPTION
**Pull request by imjorge**
Closes #821

### CODE REVIEW

File: test/runner/runner.go [hunk 1]
```diff
@@ -79,7 +79,11 @@ type Build struct {
 }
 
 func (b *Build) URL() string {
-	return "https://ci.flynn.io/builds/" + b.ID
+	url := "https://ci.flynn.io/builds/" + b.ID
+	if listenPort != "" && listenPort != "443" {
+		url = "https://ci.flynn.io:" + listenPort + "/builds/" + b.ID
```
Comment (lmars) [inline test/runner/runner.go]: Return this here, or return the non-port version after the if statement.

**Comment by imjorge** [comment]
Done.

**Comment by lmars** [comment]
Thanks!
