### PR TITLE
cli: Fix exporting apps from legacy clusters

### LINKED ISSUE #2777: export/backup fails on OS X using client v20160503.0
On OS X (10.11.3), with client v20160503.0, both backup and export are having trouble fetching artifacts. Example diagnostics as follows:

    error retrieving artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401
    error getting mariadb app artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401
    error getting flannel app artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401

Works as expected when reverting to client v20160327.0.

### PR DESCRIPTION
**Pull request by lmars**
Fixes #2777.

Tested manually by booting a `v20160327.0` cluster and using the latest CLI to export an app (and also run a cluster backup, but that is unaffected).

### CODE REVIEW

**Comment by titanous** [comment]
Looks like this supercedes #2785? /cc @jvatic

**Comment by lmars** [comment]
@titanous yes sorry I missed the other PR, I have closed in favour of mine as it has more fixes.

File: controller/types/types.go [hunk 1]
```diff
@@ -62,6 +62,8 @@ type Release struct {
 func (r *Release) ImageArtifactID() string {
 	if len(r.ArtifactIDs) > 0 {
 		return r.ArtifactIDs[0]
+	} else if r.LegacyArtifactID != "" {
+		return r.LegacyArtifactID
 	}
 	return ""
```
Comment (titanous) [inline controller/types/types.go]: No need for the else, it can be returned directly without a check.

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by titanous** [comment]
LGTM
