### PR TITLE
cli: List deployments

### LINKED ISSUE #1176: Deploys should be visible via the CLI
I should be able to see current and past deploys via the CLI, and be able to stop stuck deploys, e.g.

```
$ flynn deploy list
ID        Status   Started      Finished
312e09ee  running  5 mins ago
b1aad0f7  success  11 mins ago  10 mins ago
e95004dd  failed   22 mins ago  21 mins ago

$ flynn deploy stop 312e09ee
Deploy 312e09ee stopped
```

### PR DESCRIPTION
**Pull request by josephglanville**
List deployments along with their status, start and finish times.

Closes #1176

### CODE REVIEW

File: cli/deployment.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+usage: flynn deploy
+
+Manage app deployments
+
+Commands:
+    With no arguments, shows a list of deployments
+
+Examples:
+
+	$ flynn deploy
```
Comment (titanous) [inline cli/deployment.go]: I think we should probably call this `flynn deployment` to avoid the confusion of an action vs a namespace.

File: cli/main.go [hunk 2]
```diff
@@ -277,6 +280,14 @@ func tabWriter() *tabwriter.Writer {
 	return tabwriter.NewWriter(os.Stdout, 1, 2, 2, ' ', 0)
 }
 
+func humanTime(ts *time.Time) string {
+	var fmted string
+	if !ts.IsZero() {
```
Comment (titanous) [inline cli/main.go]: I believe this should be inverted, the exceptional path should be indented, so `if ts.IsZero() { return "" }`

File: cli/deployment.go (hunk 1 above)
Comment (josephglanville) [inline cli/deployment.go]: Yep, that was my original thought. I think I changed it to fit the initial issue but deployment does make more sense to me too.

File: cli/main.go (hunk 2 above)
Comment (josephglanville) [inline cli/main.go]: Good call.

**Comment by titanous** [comment]
This is great!

It looks like we need a test for the singleton get endpoint, there is already a `controller/deployment_test.go` file that it could be added to.

**Comment by josephglanville** [comment]
Add tests for List and Get controller endpoints.

File: controller/deployment.go [hunk 3]
```diff
@@ -81,18 +94,58 @@ func (r *DeploymentRepo) Add(data interface{}) error {
...
+                     processes, d.created_at, d.finished_at
+              FROM deployments d
+              LEFT JOIN deployment_events e1 ON d.deployment_id = e1.object_id::uuid
+              LEFT OUTER JOIN deployment_events e2 ON (d.deployment_id = e2.object_id::uuid AND e1.created_at < e2.created_at)
+              WHERE e2.created_at IS NULL AND d.app_id = $1 ORDER BY d.created_at DESC`
+	rows, err := r.db.Query(query, appID)
+	if err != nil {
+		return nil, err
+	}
+	deployments := []*ct.Deployment{}
```
Comment (titanous) [inline controller/deployment.go]: For zero values we typically declare like this to avoid an extra allocation:

```go
var deployments []*ct.Deployment
```

File: controller/deployment_test.go [hunk 4]
```diff
@@ -88,3 +89,57 @@ func (s *S) TestStreamDeployment(c *C) {
...
+	d, err = s.c.CreateDeployment(app.ID, newRelease.ID)
+
+	// test we can retrieve it
+	deployment, err := s.c.GetDeployment(d.ID)
+	c.Assert(err, IsNil)
+	c.Assert(deployment.ID, Equals, d.ID)
+	c.Assert(deployment.AppID, Equals, app.ID)
+	c.Assert(deployment.OldReleaseID, Equals, release.ID)
+	c.Assert(deployment.NewReleaseID, Equals, newRelease.ID)
+	c.Assert(reflect.DeepEqual(deployment.Processes, map[string]int{"web": 1}), Equals, true)
```
Comment (titanous) [inline controller/deployment_test.go]: It looks like this doesn't assert the status? (ditto below)

File: controller/deployment.go (hunk 3 above)
Comment (josephglanville) [inline controller/deployment.go]: Cool, will keep that in mind.

**Comment by titanous** [comment]
Would you please rebase this on the latest master? I'd like to see a test run before merging to master.

**Comment by lmars** [comment]
`CLISuite.TestDeploy` is hanging when pushing via git, and we pinned it down to the fact that the gitreceive app is being deployed shortly after bootstrap, and the router does not close the client git connection.

Although [a deployment is created](https://github.com/flynn/flynn/blob/master/bootstrap/deploy_app_action.go#L101) for gitreceive during bootstrap, [this code](https://github.com/flynn/flynn/blob/master/controller/deployment.go#L53-L60) on master prevents the deployment from actually being enqueued and subsequently worked off. That code [has been changed on this branch](https://github.com/josephglanville/flynn/blob/deployments_cli/controller/deployment.go#L53-L65), so that could be the reason gitreceive is now being deployed after bootstrap.

We also need to determine why the client git connection does not get closed when gitreceive dies.

**Comment by josephglanville** [comment]
The cause of the hang is not related to this patch set, it occurs even on master if a deploy happens early enough after bootstrap as demonstrated in #1804.

**Comment by josephglanville** [comment]
ping @titanous this should be good to go now.

**Comment by titanous** [comment]
LGTM.
