### PR TITLE
controller: Add index column to release_artifacts

### LINKED ISSUE #2797: test: ControllerSuite.TestAppDeleteCleanup failed
```
20:51:13.074 FAIL: test_controller.go:330: ControllerSuite.TestAppDeleteCleanup

++ 20:50:58.318 /bin/cp -r apps/http /tmp/check-605394647632969758/0/repo

++ 20:50:58.320 /usr/bin/git init
Initialized empty Git repository in /tmp/check-605394647632969758/0/repo/.git/

++ 20:50:58.323 /usr/bin/git add .

++ 20:50:58.325 /usr/bin/git commit -am init
[master (root-commit) 4bdaedb] init
 3 files changed, 22 insertions(+)
 create mode 100644 Godeps/Godeps.json
 create mode 100644 Procfile
 create mode 100644 main.go

++ 20:50:58.328 /home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn create app-delete-cleanup-22d38b8f
Created app-delete-cleanup-22d38b8f

++ 20:50:58.384 /usr/bin/git push flynn master
remote: -----> Building app-delete-cleanup-22d38b8f...        
remote: -----> Go app detected        
remote: -----> Checking Godeps/Godeps.json file.        
remote:  !             
remote:  !     Deprecated version of go (go1.4.2)        
remote:  !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.        
remote:  !             
remote: -----> Installing go1.4.2... done        
remote: -----> Running: godep go install -tags heroku .        
remote: -----> Discovering process types        
remote:        Procfile declares types -> web, another-web        
remote: -----> Compiled slug size is 1.7M        
remote: -----> Creating release...        
remote: =====> Application deployed        
remote: =====> Waiting for web job to start...        
remote: Failed to scale web process type        
To https://git.flynn-a1bde3de3ce1a59f.local/app-delete-cleanup-22d38b8f.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.flynn-a1bde3de3ce1a59f.local/app-delete-cleanup-22d38b8f.git'

test_controller.go:337:
    t.Assert(r.git("push", "flynn", "master"), Succeeds)
... result *main.CmdResult = &main.CmdResult{Cmd:[]string{"git", "push", "flynn", "master"}, Output:"remote: \x1b[1G\x1b[K-----> Building app-delete-cleanup-22d38b8f...        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Go app detected        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Checking Godeps/Godeps.json file.        \nremote: \x1b[1;33m !     \x1b[0m        \nremote: \x1b[1;33m !     Deprecated version of go (go1.4.2)\x1b[0m        \nremote: \x1b[1;33m !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.\x1b[0m        \nremote: \x1b[1;33m !     \x1b[0m        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Installing go1.4.2... done        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Running: godep go install -tags heroku .        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Discovering process types        \nremote: \x1b[1G\x1b[K\x1b[1G       Procfile declares types -> web, another-web        \nremote: \x1b[1G\x1b[K\x1b[1G-----> Compiled slug size is 1.7M        \nremote: \x1b[1G\x1b[K-----> Creating release...        \nremote: \x1b[1G\x1b[K=====> Application deployed        \nremote: \x1b[1G\x1b[K=====> Waiting for web job to start...        \nremote: Failed to scale web process type        \nTo https://git.flynn-a1bde3de3ce1a59f.local/app-delete-cleanup-22d38b8f.git\n ! [remote rejected] master -> master (pre-receive hook declined)\nerror: failed to push some refs to 'https://git.flynn-a1bde3de3ce1a59f.local/app-delete-cleanup-22d38b8f.git'\n", Err:(*exec.ExitError)(0xc2087d6ba0)}
```

The job is failing to start because the slug URL is set as the image artifact:

```
t=2016-05-07T20:51:12+0000 lvl=info msg="running job" app=host pid=1180 host.id=297193c0 fn=AddJob job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec
t=2016-05-07T20:51:12+0000 lvl=info msg="starting job" app=host pid=1180 host.id=297193c0 component=backend backend=libvirt-lxc fn=run job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec job.artifact.uri=http://blobstore.discoverd/23d099f5-1937-40ec-bdd4-0ed8e56adbb8/slug.tgz job.cmd="[start web]"
t=2016-05-07T20:51:12+0000 lvl=info msg="obtained ip" app=host pid=1180 host.id=297193c0 component=backend backend=libvirt-lxc fn=run job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec network=100.100.57.0/24 ip=100.100.57.119
t=2016-05-07T20:51:12+0000 lvl=info msg="pulling image" app=host pid=1180 host.id=297193c0 component=backend backend=libvirt-lxc fn=run job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec
t=2016-05-07T20:51:12+0000 lvl=eror msg="error pulling image" app=host pid=1180 host.id=297193c0 component=backend backend=libvirt-lxc fn=run job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec err="registry: name must be provided"
t=2016-05-07T20:51:12+0000 lvl=eror msg="error running job" app=host pid=1180 host.id=297193c0 fn=AddJob job.id=297193c0-a4ca214c-b316-43c4-9046-e4a27c2714ec err="registry: name must be provided"
```

### PR DESCRIPTION
**Pull request by lmars**
We were seeing some jobs being started with the artifacts ordered incorrectly (i.e. the image artifact was the file artifact and vice versa). Adding an explicit array index should fix this.

Fixes #2797.

/cc @titanous @josephglanville

### CODE REVIEW

File: controller/schema.go [hunk 1]
```diff
@@ -360,6 +360,26 @@ $$ LANGUAGE plpgsql`,
...
+			FOR release IN SELECT DISTINCT(release_id) FROM release_artifacts LOOP
+				i := 0;
+				FOR row IN SELECT * FROM release_artifacts WHERE release_id = release ORDER BY created_at ASC LOOP
+					UPDATE release_artifacts SET index = i WHERE release_id = release AND artifact_id = row.artifact_id;
+					i := i + 1;
+				END LOOP;
+			END LOOP;
+		END $$`,
+		`ALTER TABLE release_artifacts ALTER COLUMN index SET NOT NULL`,
+	)
```
Comment (titanous) [inline controller/schema.go]: Should there also be a unique constraint across `(release_id, index)`?

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by josephglanville** [comment]
LGTM
