### PR TITLE
all: Migrate to pgx

### LINKED ISSUE #989: Use pgx in controller instead of pq
We're standardizing on pgx in the codebase, so all uses of pq in the controller should be converted to pgx.

### LINKED ISSUE #1709: controller: Create and enqueue deployments in a DB transaction
If enqueueing a deployment job fails, an error is returned but the deployment record remains in the controller database, which prevents subsequent deploys for the given app (see #1704).

We should fix [this TODO](https://github.com/flynn/flynn/blob/master/controller/deployment.go#L73) and create / enqueue deployments in a DB transaction.

### LINKED ISSUE #1915: test: Postgres deploy fails with "cannot execute INSERT in a read-only transaction"
https://ci.flynn.io/builds/20150929201125-7f5070ff

### PR DESCRIPTION
**Pull request by josephglanville**
This migrates remaining users of pq/go-sql to pgx.

- [x] Migrate pkg/postgres
- [x] Migrate router
- [x] Migrate blobstore
- [x] Migrate controller
- [x] Migrate pkg/postgres/listener
- [x] Migrate pgtestutils
- [x] Migrate and fix tests

Closes #989
Closes #1709
Closes #1915

### CODE REVIEW

**Comment by josephglanville** [comment]
Running into issues with pgx not being able to Scan into **time.Time, might require further patches to pgx.

**Comment by titanous** [comment]
Is it a `**time.Time` issue or does it not currently support pointers to pointers?

**Comment by josephglanville** [comment]
The later I think. My golang metaprogramming foo isn't quite there yet though so I don't know how to implement it. If you have some pointers on how to go about it though I would definitely take a swing at it.

**Comment by josephglanville** [comment]
All the actual conversions have happened now. However hitting an issue with events and json encoding/decoding of json.RawMessage. Easily reproduced in the unit tests.

There is also now a race condition in postgres.Wait() where the leader has registered with discoverd and receiving traffic but password authentication fails for the Flynn user. This causes the postgres appliance web process to crash. Need to work out what to do there, maybe just retry 3x or something until auth succeeds?
I have dropped in a 1 second delay for now as that is enough to avoid it during testing but it needs to be resolved.

**Comment by lmars** [comment]
@josephglanville looks like `Godeps.json` needs updating

**Comment by josephglanville** [comment]
@lmars yeah, things are a bit hacked atm until UUID patch is merged upstream.

File: pkg/postgres/postgres.go [hunk 1]
```diff
@@ -51,7 +59,10 @@ func Wait(service, dsn string) *DB {
 	stream.Close()
 	// TODO(titanous): handle discoverd disconnection
 
-	db, err := Open(service, dsn)
+	// TODO(jpg): Race condition between DB registering with discoverd and being able
+	// to authenticate with password. Resolve this correctly before merging.
```
Comment (lmars) [inline pkg/postgres/postgres.go]: I would just wrap this in `attempt.Strategy.Run` with a comment as to why.

Comment (titanous) [inline pkg/postgres/postgres.go]: I think a good option is to add `WaitForUserExistence` to https://github.com/flynn/flynn/blob/master/appliance/postgresql/client/client.go

Comment (josephglanville) [inline pkg/postgres/postgres.go]: That sounds cleaner.

Comment (josephglanville) [inline pkg/postgres/postgres.go]: That would require pulling the pgmanager client into pkg/postgres though. Which probably means we should use it to wait for read/write state as well. Not sure if it's a good idea to do all of that in this change set though, it's already getting unwieldy and hard to track down bugs.
This along with prepared statements and changing fixing up the deployment transactions etc I think should go in after.

Comment (titanous) [inline pkg/postgres/postgres.go]: That's find, drop an `attempt` in and add some TODOs.

**Comment by josephglanville** [comment]
Used `attempt` to close the user exists race for now, put in TODO to deal with correctly using pgmanager.

Fixed up some of the event stuff, still having issues with "unexpected close of deployment event stream".

**Comment by josephglanville** [comment]
Had another chance to try get this working. Converted the queries to prepared statements on suspicion that preparing queries on the fly was causing issues.
Unfortunately that means this is probably on hold until https://github.com/jackc/pgx/issues/93 can be resolved.
I will probably go ahead and do the other enhancements like cleanup up deployment transactional consistency etc anyways though.

**Comment by josephglanville** [comment]
Fixing the leaking listener connections has fixed the bits that looked like bugs in pgx however this is likely working around a more sinister issue in pgx itself so I will continue to try fix bugs there.

Now there is 2 remaining issues.
* There are a few cases where somehow the connection pool gets closed. This has been noted in router issues before (which has always used pgx)
* There are also some cases where lack of retry logic is causing issues, go-sql had retry logic built in, pgx does not.

**Comment by josephglanville** [comment]
Managed to get the failure down to a minimal test case:
```
SINGLETON=false ./script/bootstrap-flynn
flynn add --force
flynn -a postgres env set test=test # to trigger a postgres deployment
```

Now, what will happen is the postgres processes will fail to exit during the deployment and the deployment will fail waiting for the down events (as they will never come).
However I am not sold on this being the only problem as after this the controller and router seem to lock up.
From the router log I can see the sync connection dying but it's not clear if it manages to re-establish it.
When inspecting controller web processes I can see many goroutines stuck on trying to acquire from the pgx pool blocked on a semaphore.

**Comment by josephglanville** [comment]
Digging into the postgres deployment failure has revealed the postgres deployment task gets stuck trying to stop the old jobs by scaling the old formation:
```
goroutine 30 [select, 5 minutes]:
net/http.(*persistConn).roundTrip(0xc2080ae790, 0xc208118de0, 0x0, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc2080601b0, 0xc2080f1110, 0xc208064c80, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/transport.go:235 +0x558
net/http.send(0xc2080f1110, 0x7f8777cd7d80, 0xc2080601b0, 0x75, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803aea0, 0xc2080f1110, 0x75, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803aea0, 0xc2080f1110, 0x8c28f0, 0x0, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc20803aea0, 0xc2080f1110, 0x3, 0x0, 0x0)
	/vagrant/util/_toolchain/go/src/net/http/client.go:177 +0x192
github.com/flynn/flynn/pkg/httpclient.(*Client).rawReq(0xc2080420a0, 0x7fd8d0, 0x3, 0xc208064c00, 0x75, 0x0, 0x6ce860, 0xc208127680, 0x6ce860, 0xc208127680, ...)
	/home/vagrant/go/src/github.com/flynn/flynn/pkg/httpclient/json.go:102 +0x123
github.com/flynn/flynn/pkg/httpclient.(*Client).RawReq(0xc2080420a0, 0x7fd8d0, 0x3, 0xc20808a9c0, 0x5a, 0x0, 0x6ce860, 0xc208127680, 0x6ce860, 0xc208127680, ...)
	/home/vagrant/go/src/github.com/flynn/flynn/pkg/httpclient/json.go:84 +0x104
github.com/flynn/flynn/pkg/httpclient.(*Client).Send(0xc2080420a0, 0x7fd8d0, 0x3, 0xc20808a9c0, 0x5a, 0x6ce860, 0xc208127680, 0x6ce860, 0xc208127680, 0x0, ...)
	/home/vagrant/go/src/github.com/flynn/flynn/pkg/httpclient/json.go:221 +0xbc
github.com/flynn/flynn/controller/client.(*Client).send(0xc208040048, 0x7fd8d0, 0x3, 0xc20808a9c0, 0x5a, 0x6ce860, 0xc208127680, 0x6ce860, 0xc208127680, 0x0, ...)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/client/client.go:732 +0x114
github.com/flynn/flynn/controller/client.(*Client).Put(0xc208040048, 0xc20808a9c0, 0x5a, 0x6ce860, 0xc208127680, 0x6ce860, 0xc208127680, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/client/client.go:715 +0x98
github.com/flynn/flynn/controller/client.(*Client).PutFormation(0xc208040048, 0xc208127680, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/client/client.go:302 +0x201
github.com/flynn/flynn/controller/worker/deployment.(*DeployJob).deployPostgres(0xc208064780, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/worker/deployment/postgres.go:216 +0x10ed
github.com/flynn/flynn/controller/worker/deployment.*DeployJob.(github.com/flynn/flynn/controller/worker/deployment.deployPostgres)·fm(0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/worker/deployment/job.go:52 +0x39
github.com/flynn/flynn/controller/worker/deployment.(*DeployJob).Perform(0xc208064780, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/worker/deployment/job.go:182 +0x1794
github.com/flynn/flynn/controller/worker/deployment.(*context).HandleDeployment(0xc2080ba2c0, 0xc20810b040, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/worker/deployment/context.go:112 +0x17f7
github.com/flynn/flynn/controller/worker/deployment.*context.HandleDeployment·fm(0xc20810b040, 0x0, 0x0)
	/home/vagrant/go/src/github.com/flynn/flynn/controller/worker/deployment/context.go:26 +0x43
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go.(*Worker).WorkOne(0xc208042910, 0xc20808ac01)
	/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go/worker.go:116 +0x5c9
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go.(*Worker).Work(0xc208042910)
	/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go/worker.go:82 +0x1e1
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go.*Worker.Work·fm()
	/home/vagrant/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/que-go/worker.go:197 +0x27
created by time.goFunc
	/vagrant/util/_toolchain/go/src/time/sleep.go:129 +0x4b
```
As we can see it called PutFormation which then got stuck talking to the controller.

So one of the controller processes was hung. Pulling the goroutine stacktraces gives me this: 
Now I am not sure what is wrong yet but we can already see that there are tons of go-routines blocked on trying to acquire a new connection from the pgx pool.
What we need to work out is why it's not connecting new connections?

I do have a feeling this might be a strange interaction also involving the router but I am not sure yet.

Anyways, at the least this explains why the postgres jobs aren't stopped, it's because PutFormation never succeeds so the scheduler never tells flynn-host to stop them. However the postgres processes themselves are shutdown because PgManager has already shut them down and gotten the new cluster fully running.

**Comment by josephglanville** [comment]
Ok, we are green now!

Ready for review @titanous @lmars

File: test/test_postgres.go [hunk 2]
```diff
@@ -223,17 +223,26 @@ func (s *PostgresSuite) testDeploy(t *c.C, d *pgDeploy) {
...
+		User:     "flynn",
+		Password: release.Env["PGPASSWORD"],
+		Database: dbname,
+	}, nil)
 	defer db.Close()
 	t.Assert(db.Exec(`CREATE TABLE deploy_test ( data text)`), c.IsNil)
 	assertWriteable := func() {
 		debug(t, "writing to postgres database")
-		t.Assert(db.Exec(`INSERT INTO deploy_test (data) VALUES ('data')`), c.IsNil)
+		t.Assert(db.ExecRetry(`INSERT INTO deploy_test (data) VALUES ('data')`), c.IsNil)
```
Comment (lmars) [inline test/test_postgres.go]: Should `ExecRetry` be the default behaviour of `Exec`? We want to be able to deploy Postgres during an update with minimal impact on the cluster.

**Comment by lmars** [comment]
LGTM pending comment, great work!

File: test/test_postgres.go (hunk 2 above)
Comment (josephglanville) [inline test/test_postgres.go]: Not unless we ensure any queries executed with it are idempotent.
It would require a more sophisticated retry system that can work out whether or not the query was fully sent to the server or not to know if it's safe to retry, otherwise we might retry a query that did indeed execute already but we lost the connection before we got confirmation.

Comment (lmars) [inline test/test_postgres.go]: Understood

**Comment by titanous** [comment]
LGTM!
